// Code generated by 'go generate'; DO NOT EDIT.

package time

import (
	"github.com/gad-lang/gad"
)

// funcPTRO is a generated function to make gad.CallableFunc.
// Source: funcPTRO(t *Time) (ret gad.Object)
func funcPTRO(fn func(*Time) gad.Object) gad.CallableFunc {
	return func(c gad.Call) (ret gad.Object, err error) {
		if err := c.Args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}

		ret = fn(t)
		return
	}
}

// funcPTi64RO is a generated function to make gad.CallableFunc.
// Source: funcPTi64RO(t *Time, d int64) (ret gad.Object)
func funcPTi64RO(fn func(*Time, int64) gad.Object) gad.CallableFunc {
	return func(c gad.Call) (ret gad.Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		d, ok := gad.ToGoInt64(c.Args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", c.Args.Get(1).Type().Name())
		}

		ret = fn(t, d)
		return
	}
}

// funcPTTRO is a generated function to make gad.CallableFunc.
// Source: funcPTTRO(t1 *Time, t2 *Time) (ret gad.Object)
func funcPTTRO(fn func(*Time, *Time) gad.Object) gad.CallableFunc {
	return func(c gad.Call) (ret gad.Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		t1, ok := ToTime(c.Args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		t2, ok := ToTime(c.Args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "time", c.Args.Get(1).Type().Name())
		}

		ret = fn(t1, t2)
		return
	}
}

// funcPTiiiRO is a generated function to make gad.CallableFunc.
// Source: funcPTiiiRO(t *Time, i1 int, i2 int, i3 int) (ret gad.Object)
func funcPTiiiRO(fn func(*Time, int, int, int) gad.Object) gad.CallableFunc {
	return func(c gad.Call) (ret gad.Object, err error) {
		if err := c.Args.CheckLen(4); err != nil {
			return gad.Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		i1, ok := gad.ToGoInt(c.Args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", c.Args.Get(1).Type().Name())
		}
		i2, ok := gad.ToGoInt(c.Args.Get(2))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("3rd", "int", c.Args.Get(2).Type().Name())
		}
		i3, ok := gad.ToGoInt(c.Args.Get(3))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("4th", "int", c.Args.Get(3).Type().Name())
		}

		ret = fn(t, i1, i2, i3)
		return
	}
}

// funcPTsRO is a generated function to make gad.CallableFunc.
// Source: funcPTsRO(t *Time, s string) (ret gad.Object)
func funcPTsRO(fn func(*Time, string) gad.Object) gad.CallableFunc {
	return func(c gad.Call) (ret gad.Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		s, ok := gad.ToGoString(c.Args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", c.Args.Get(1).Type().Name())
		}

		ret = fn(t, s)
		return
	}
}

// funcPTb2sRO is a generated function to make gad.CallableFunc.
// Source: funcPTb2sRO(t *Time, b []byte, s string) (ret gad.Object)
func funcPTb2sRO(fn func(*Time, []byte, string) gad.Object) gad.CallableFunc {
	return func(c gad.Call) (ret gad.Object, err error) {
		if err := c.Args.CheckLen(3); err != nil {
			return gad.Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		b, ok := gad.ToGoByteSlice(c.Args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "bytes", c.Args.Get(1).Type().Name())
		}
		s, ok := gad.ToGoString(c.Args.Get(2))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("3rd", "string", c.Args.Get(2).Type().Name())
		}

		ret = fn(t, b, s)
		return
	}
}

// funcPTLRO is a generated function to make gad.CallableFunc.
// Source: funcPTLRO(t *Time, loc *Location) (ret gad.Object)
func funcPTLRO(fn func(*Time, *Location) gad.Object) gad.CallableFunc {
	return func(c gad.Call) (ret gad.Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		loc, ok := ToLocation(c.Args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "location", c.Args.Get(1).Type().Name())
		}

		ret = fn(t, loc)
		return
	}
}
