version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errchkjson
    - grouper
    - misspell
    - nilerr
    - nilnil
    - predeclared
    - unconvert
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    misspell:
      locale: US
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
