// Code generated by 'go generate'; DO NOT EDIT.
package gad

import "github.com/gad-lang/gad/token"

var (
	TBinaryOperatorAdd         = BinaryOperatorType(token.Add)         // +
	TBinaryOperatorSub         = BinaryOperatorType(token.Sub)         // -
	TBinaryOperatorMul         = BinaryOperatorType(token.Mul)         // *
	TBinaryOperatorPow         = BinaryOperatorType(token.Pow)         // **
	TBinaryOperatorQuo         = BinaryOperatorType(token.Quo)         // /
	TBinaryOperatorRem         = BinaryOperatorType(token.Rem)         // %
	TBinaryOperatorAnd         = BinaryOperatorType(token.And)         // &
	TBinaryOperatorOr          = BinaryOperatorType(token.Or)          // |
	TBinaryOperatorXor         = BinaryOperatorType(token.Xor)         // ^
	TBinaryOperatorShl         = BinaryOperatorType(token.Shl)         // <<
	TBinaryOperatorShr         = BinaryOperatorType(token.Shr)         // >>
	TBinaryOperatorAndNot      = BinaryOperatorType(token.AndNot)      // &^
	TBinaryOperatorLAnd        = BinaryOperatorType(token.LAnd)        // &&
	TBinaryOperatorEqual       = BinaryOperatorType(token.Equal)       // ==
	TBinaryOperatorNotEqual    = BinaryOperatorType(token.NotEqual)    // !=
	TBinaryOperatorLess        = BinaryOperatorType(token.Less)        // <
	TBinaryOperatorGreater     = BinaryOperatorType(token.Greater)     // >
	TBinaryOperatorLessEq      = BinaryOperatorType(token.LessEq)      // <=
	TBinaryOperatorGreaterEq   = BinaryOperatorType(token.GreaterEq)   // >=
	TBinaryOperatorTilde       = BinaryOperatorType(token.Tilde)       // ~
	TBinaryOperatorDoubleTilde = BinaryOperatorType(token.DoubleTilde) // ~~
	TBinaryOperatorTripleTilde = BinaryOperatorType(token.TripleTilde) // ~~~

	TSelfAssignOperatorAdd    = SelfAssignOperatorType(token.Add)    // +
	TSelfAssignOperatorInc    = SelfAssignOperatorType(token.Inc)    // ++
	TSelfAssignOperatorSub    = SelfAssignOperatorType(token.Sub)    // -
	TSelfAssignOperatorDec    = SelfAssignOperatorType(token.Dec)    // --
	TSelfAssignOperatorMul    = SelfAssignOperatorType(token.Mul)    // *
	TSelfAssignOperatorPow    = SelfAssignOperatorType(token.Pow)    // **
	TSelfAssignOperatorQuo    = SelfAssignOperatorType(token.Quo)    // /
	TSelfAssignOperatorRem    = SelfAssignOperatorType(token.Rem)    // %
	TSelfAssignOperatorAnd    = SelfAssignOperatorType(token.And)    // &
	TSelfAssignOperatorOr     = SelfAssignOperatorType(token.Or)     // |
	TSelfAssignOperatorXor    = SelfAssignOperatorType(token.Xor)    // ^
	TSelfAssignOperatorShl    = SelfAssignOperatorType(token.Shl)    // <<
	TSelfAssignOperatorShr    = SelfAssignOperatorType(token.Shr)    // >>
	TSelfAssignOperatorAndNot = SelfAssignOperatorType(token.AndNot) // &^
	TSelfAssignOperatorLOr    = SelfAssignOperatorType(token.LOr)    // ||
)

func init() {
	add := func(bt BuiltinType, t ObjectType) {
		BuiltinObjects[bt] = t
		BuiltinsMap[t.Name()] = bt
	}
	add(BuiltinBinaryOperatorAdd, TBinaryOperatorAdd)
	add(BuiltinBinaryOperatorSub, TBinaryOperatorSub)
	add(BuiltinBinaryOperatorMul, TBinaryOperatorMul)
	add(BuiltinBinaryOperatorPow, TBinaryOperatorPow)
	add(BuiltinBinaryOperatorQuo, TBinaryOperatorQuo)
	add(BuiltinBinaryOperatorRem, TBinaryOperatorRem)
	add(BuiltinBinaryOperatorAnd, TBinaryOperatorAnd)
	add(BuiltinBinaryOperatorOr, TBinaryOperatorOr)
	add(BuiltinBinaryOperatorXor, TBinaryOperatorXor)
	add(BuiltinBinaryOperatorShl, TBinaryOperatorShl)
	add(BuiltinBinaryOperatorShr, TBinaryOperatorShr)
	add(BuiltinBinaryOperatorAndNot, TBinaryOperatorAndNot)
	add(BuiltinBinaryOperatorLAnd, TBinaryOperatorLAnd)
	add(BuiltinBinaryOperatorEqual, TBinaryOperatorEqual)
	add(BuiltinBinaryOperatorNotEqual, TBinaryOperatorNotEqual)
	add(BuiltinBinaryOperatorLess, TBinaryOperatorLess)
	add(BuiltinBinaryOperatorGreater, TBinaryOperatorGreater)
	add(BuiltinBinaryOperatorLessEq, TBinaryOperatorLessEq)
	add(BuiltinBinaryOperatorGreaterEq, TBinaryOperatorGreaterEq)
	add(BuiltinBinaryOperatorTilde, TBinaryOperatorTilde)
	add(BuiltinBinaryOperatorDoubleTilde, TBinaryOperatorDoubleTilde)
	add(BuiltinBinaryOperatorTripleTilde, TBinaryOperatorTripleTilde)

	add(BuiltinSelfAssignOperatorAdd, TSelfAssignOperatorAdd)
	add(BuiltinSelfAssignOperatorInc, TSelfAssignOperatorInc)
	add(BuiltinSelfAssignOperatorSub, TSelfAssignOperatorSub)
	add(BuiltinSelfAssignOperatorDec, TSelfAssignOperatorDec)
	add(BuiltinSelfAssignOperatorMul, TSelfAssignOperatorMul)
	add(BuiltinSelfAssignOperatorPow, TSelfAssignOperatorPow)
	add(BuiltinSelfAssignOperatorQuo, TSelfAssignOperatorQuo)
	add(BuiltinSelfAssignOperatorRem, TSelfAssignOperatorRem)
	add(BuiltinSelfAssignOperatorAnd, TSelfAssignOperatorAnd)
	add(BuiltinSelfAssignOperatorOr, TSelfAssignOperatorOr)
	add(BuiltinSelfAssignOperatorXor, TSelfAssignOperatorXor)
	add(BuiltinSelfAssignOperatorShl, TSelfAssignOperatorShl)
	add(BuiltinSelfAssignOperatorShr, TSelfAssignOperatorShr)
	add(BuiltinSelfAssignOperatorAndNot, TSelfAssignOperatorAndNot)
	add(BuiltinSelfAssignOperatorLOr, TSelfAssignOperatorLOr)
}
