// Code generated by 'go generate'; DO NOT EDIT.

package gad

// FuncPTRO is a generated function to make CallableFunc.
// Source: FuncPTRO(t *Time) (ret Object)
func FuncPTRO(fn func(*Time) Object) CallableFunc {
	return func(c Call) (ret Object, err error) {
		if err := c.Args.CheckLen(1); err != nil {
			return Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return Nil, NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}

		ret = fn(t)
		return
	}
}

// FuncPTi64RO is a generated function to make CallableFunc.
// Source: FuncPTi64RO(t *Time, d int64) (ret Object)
func FuncPTi64RO(fn func(*Time, int64) Object) CallableFunc {
	return func(c Call) (ret Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return Nil, NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		d, ok := ToGoInt64(c.Args.Get(1))
		if !ok {
			return Nil, NewArgumentTypeError("2nd", "int", c.Args.Get(1).Type().Name())
		}

		ret = fn(t, d)
		return
	}
}

// FuncPTTRO is a generated function to make CallableFunc.
// Source: FuncPTTRO(t1 *Time, t2 *Time) (ret Object)
func FuncPTTRO(fn func(*Time, *Time) Object) CallableFunc {
	return func(c Call) (ret Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return Nil, err
		}

		t1, ok := ToTime(c.Args.Get(0))
		if !ok {
			return Nil, NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		t2, ok := ToTime(c.Args.Get(1))
		if !ok {
			return Nil, NewArgumentTypeError("2nd", "time", c.Args.Get(1).Type().Name())
		}

		ret = fn(t1, t2)
		return
	}
}

// FuncPTiiiRO is a generated function to make CallableFunc.
// Source: FuncPTiiiRO(t *Time, i1 int, i2 int, i3 int) (ret Object)
func FuncPTiiiRO(fn func(*Time, int, int, int) Object) CallableFunc {
	return func(c Call) (ret Object, err error) {
		if err := c.Args.CheckLen(4); err != nil {
			return Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return Nil, NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		i1, ok := ToGoInt(c.Args.Get(1))
		if !ok {
			return Nil, NewArgumentTypeError("2nd", "int", c.Args.Get(1).Type().Name())
		}
		i2, ok := ToGoInt(c.Args.Get(2))
		if !ok {
			return Nil, NewArgumentTypeError("3rd", "int", c.Args.Get(2).Type().Name())
		}
		i3, ok := ToGoInt(c.Args.Get(3))
		if !ok {
			return Nil, NewArgumentTypeError("4th", "int", c.Args.Get(3).Type().Name())
		}

		ret = fn(t, i1, i2, i3)
		return
	}
}

// FuncPTsRO is a generated function to make CallableFunc.
// Source: FuncPTsRO(t *Time, s string) (ret Object)
func FuncPTsRO(fn func(*Time, string) Object) CallableFunc {
	return func(c Call) (ret Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return Nil, NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		s, ok := ToGoString(c.Args.Get(1))
		if !ok {
			return Nil, NewArgumentTypeError("2nd", "str", c.Args.Get(1).Type().Name())
		}

		ret = fn(t, s)
		return
	}
}

// FuncPTb2sRO is a generated function to make CallableFunc.
// Source: FuncPTb2sRO(t *Time, b []byte, s string) (ret Object)
func FuncPTb2sRO(fn func(*Time, []byte, string) Object) CallableFunc {
	return func(c Call) (ret Object, err error) {
		if err := c.Args.CheckLen(3); err != nil {
			return Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return Nil, NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		b, ok := ToGoByteSlice(c.Args.Get(1))
		if !ok {
			return Nil, NewArgumentTypeError("2nd", "bytes", c.Args.Get(1).Type().Name())
		}
		s, ok := ToGoString(c.Args.Get(2))
		if !ok {
			return Nil, NewArgumentTypeError("3rd", "str", c.Args.Get(2).Type().Name())
		}

		ret = fn(t, b, s)
		return
	}
}

// FuncPTLRO is a generated function to make CallableFunc.
// Source: FuncPTLRO(t *Time, loc *Location) (ret Object)
func FuncPTLRO(fn func(*Time, *Location) Object) CallableFunc {
	return func(c Call) (ret Object, err error) {
		if err := c.Args.CheckLen(2); err != nil {
			return Nil, err
		}

		t, ok := ToTime(c.Args.Get(0))
		if !ok {
			return Nil, NewArgumentTypeError("1st", "time", c.Args.Get(0).Type().Name())
		}
		loc, ok := ToLocation(c.Args.Get(1))
		if !ok {
			return Nil, NewArgumentTypeError("2nd", "Location", c.Args.Get(1).Type().Name())
		}

		ret = fn(t, loc)
		return
	}
}
