// Code generated by 'go generate'; DO NOT EDIT.

package gad

import "github.com/gad-lang/gad/token"

// ObjectWithAddBinOperator is implemented by an object that handles the `+`
// binary operator as the left operand.
type ObjectWithAddBinOperator interface {
	BinOpAdd(vm *VM, right Object) (Object, error)
}

// ObjectWithSubBinOperator is implemented by an object that handles the `-`
// binary operator as the left operand.
type ObjectWithSubBinOperator interface {
	BinOpSub(vm *VM, right Object) (Object, error)
}

// ObjectWithMulBinOperator is implemented by an object that handles the `*`
// binary operator as the left operand.
type ObjectWithMulBinOperator interface {
	BinOpMul(vm *VM, right Object) (Object, error)
}

// ObjectWithPowBinOperator is implemented by an object that handles the `**`
// binary operator as the left operand.
type ObjectWithPowBinOperator interface {
	BinOpPow(vm *VM, right Object) (Object, error)
}

// ObjectWithQuoBinOperator is implemented by an object that handles the `/`
// binary operator as the left operand.
type ObjectWithQuoBinOperator interface {
	BinOpQuo(vm *VM, right Object) (Object, error)
}

// ObjectWithRemBinOperator is implemented by an object that handles the `%`
// binary operator as the left operand.
type ObjectWithRemBinOperator interface {
	BinOpRem(vm *VM, right Object) (Object, error)
}

// ObjectWithAndBinOperator is implemented by an object that handles the `&`
// binary operator as the left operand.
type ObjectWithAndBinOperator interface {
	BinOpAnd(vm *VM, right Object) (Object, error)
}

// ObjectWithOrBinOperator is implemented by an object that handles the `|`
// binary operator as the left operand.
type ObjectWithOrBinOperator interface {
	BinOpOr(vm *VM, right Object) (Object, error)
}

// ObjectWithXorBinOperator is implemented by an object that handles the `^`
// binary operator as the left operand.
type ObjectWithXorBinOperator interface {
	BinOpXor(vm *VM, right Object) (Object, error)
}

// ObjectWithShlBinOperator is implemented by an object that handles the `<<`
// binary operator as the left operand.
type ObjectWithShlBinOperator interface {
	BinOpShl(vm *VM, right Object) (Object, error)
}

// ObjectWithShrBinOperator is implemented by an object that handles the `>>`
// binary operator as the left operand.
type ObjectWithShrBinOperator interface {
	BinOpShr(vm *VM, right Object) (Object, error)
}

// ObjectWithAndNotBinOperator is implemented by an object that handles the `&^`
// binary operator as the left operand.
type ObjectWithAndNotBinOperator interface {
	BinOpAndNot(vm *VM, right Object) (Object, error)
}

// ObjectWithLAndBinOperator is implemented by an object that handles the `&&`
// binary operator as the left operand.
type ObjectWithLAndBinOperator interface {
	BinOpLAnd(vm *VM, right Object) (Object, error)
}

// ObjectWithEqualBinOperator is implemented by an object that handles the `==`
// binary operator as the left operand.
type ObjectWithEqualBinOperator interface {
	BinOpEqual(vm *VM, right Object) (Object, error)
}

// ObjectWithNotEqualBinOperator is implemented by an object that handles the `!=`
// binary operator as the left operand.
type ObjectWithNotEqualBinOperator interface {
	BinOpNotEqual(vm *VM, right Object) (Object, error)
}

// ObjectWithLessBinOperator is implemented by an object that handles the `<`
// binary operator as the left operand.
type ObjectWithLessBinOperator interface {
	BinOpLess(vm *VM, right Object) (Object, error)
}

// ObjectWithGreaterBinOperator is implemented by an object that handles the `>`
// binary operator as the left operand.
type ObjectWithGreaterBinOperator interface {
	BinOpGreater(vm *VM, right Object) (Object, error)
}

// ObjectWithLessEqBinOperator is implemented by an object that handles the `<=`
// binary operator as the left operand.
type ObjectWithLessEqBinOperator interface {
	BinOpLessEq(vm *VM, right Object) (Object, error)
}

// ObjectWithGreaterEqBinOperator is implemented by an object that handles the `>=`
// binary operator as the left operand.
type ObjectWithGreaterEqBinOperator interface {
	BinOpGreaterEq(vm *VM, right Object) (Object, error)
}

// ObjectWithTildeBinOperator is implemented by an object that handles the `~`
// binary operator as the left operand.
type ObjectWithTildeBinOperator interface {
	BinOpTilde(vm *VM, right Object) (Object, error)
}

// ObjectWithDoubleTildeBinOperator is implemented by an object that handles the `~~`
// binary operator as the left operand.
type ObjectWithDoubleTildeBinOperator interface {
	BinOpDoubleTilde(vm *VM, right Object) (Object, error)
}

// ObjectWithTripleTildeBinOperator is implemented by an object that handles the `~~~`
// binary operator as the left operand.
type ObjectWithTripleTildeBinOperator interface {
	BinOpTripleTilde(vm *VM, right Object) (Object, error)
}

// ObjectWithDotDotBinOperator is implemented by an object that handles the `..`
// binary operator as the left operand.
type ObjectWithDotDotBinOperator interface {
	BinOpDotDot(vm *VM, right Object) (Object, error)
}

// ObjectWithTripleLessBinOperator is implemented by an object that handles the `<<<`
// binary operator as the left operand.
type ObjectWithTripleLessBinOperator interface {
	BinOpTripleLess(vm *VM, right Object) (Object, error)
}

// ObjectWithTripleGreaterBinOperator is implemented by an object that handles the `>>>`
// binary operator as the left operand.
type ObjectWithTripleGreaterBinOperator interface {
	BinOpTripleGreater(vm *VM, right Object) (Object, error)
}

// ObjectWithDoubleModBinOperator is implemented by an object that handles the `%%`
// binary operator as the left operand.
type ObjectWithDoubleModBinOperator interface {
	BinOpDoubleMod(vm *VM, right Object) (Object, error)
}

// ObjectWithLambdaBinOperator is implemented by an object that handles the `=>`
// binary operator as the left operand.
type ObjectWithLambdaBinOperator interface {
	BinOpLambda(vm *VM, right Object) (Object, error)
}

// ObjectWithSameBinOperator is implemented by an object that handles the `===`
// binary operator as the left operand.
type ObjectWithSameBinOperator interface {
	BinOpSame(vm *VM, right Object) (Object, error)
}

// ObjectWithNotSameBinOperator is implemented by an object that handles the `!==`
// binary operator as the left operand.
type ObjectWithNotSameBinOperator interface {
	BinOpNotSame(vm *VM, right Object) (Object, error)
}

// ObjectWithIncBinOperator is implemented by an object that handles the `++`
// binary operator as the left operand.
type ObjectWithIncBinOperator interface {
	BinOpInc(vm *VM, right Object) (Object, error)
}

// ObjectWithDecBinOperator is implemented by an object that handles the `--`
// binary operator as the left operand.
type ObjectWithDecBinOperator interface {
	BinOpDec(vm *VM, right Object) (Object, error)
}

// ObjectWithInBinOperator is implemented by an object that handles the `in`
// binary operator as the left operand.
type ObjectWithInBinOperator interface {
	BinOpIn(vm *VM, right Object) (Object, error)
}

// ObjectWithAinBinOperator is implemented by an object that handles the `ain`
// binary operator as the left operand.
type ObjectWithAinBinOperator interface {
	BinOpAin(vm *VM, right Object) (Object, error)
}

// binOpObject dispatches a binary operator to left's typed
// ObjectWith{Op}BinOperator implementation. handled is false when left does
// not implement the operator's interface.
func binOpObject(vm *VM, op BinaryOperatorType, left, right Object) (ret Object, err error, handled bool) {
	switch op.Token() {
	case token.Add:
		if h, ok := left.(ObjectWithAddBinOperator); ok {
			ret, err = h.BinOpAdd(vm, right)
			handled = true
		}
	case token.Sub:
		if h, ok := left.(ObjectWithSubBinOperator); ok {
			ret, err = h.BinOpSub(vm, right)
			handled = true
		}
	case token.Mul:
		if h, ok := left.(ObjectWithMulBinOperator); ok {
			ret, err = h.BinOpMul(vm, right)
			handled = true
		}
	case token.Pow:
		if h, ok := left.(ObjectWithPowBinOperator); ok {
			ret, err = h.BinOpPow(vm, right)
			handled = true
		}
	case token.Quo:
		if h, ok := left.(ObjectWithQuoBinOperator); ok {
			ret, err = h.BinOpQuo(vm, right)
			handled = true
		}
	case token.Rem:
		if h, ok := left.(ObjectWithRemBinOperator); ok {
			ret, err = h.BinOpRem(vm, right)
			handled = true
		}
	case token.And:
		if h, ok := left.(ObjectWithAndBinOperator); ok {
			ret, err = h.BinOpAnd(vm, right)
			handled = true
		}
	case token.Or:
		if h, ok := left.(ObjectWithOrBinOperator); ok {
			ret, err = h.BinOpOr(vm, right)
			handled = true
		}
	case token.Xor:
		if h, ok := left.(ObjectWithXorBinOperator); ok {
			ret, err = h.BinOpXor(vm, right)
			handled = true
		}
	case token.Shl:
		if h, ok := left.(ObjectWithShlBinOperator); ok {
			ret, err = h.BinOpShl(vm, right)
			handled = true
		}
	case token.Shr:
		if h, ok := left.(ObjectWithShrBinOperator); ok {
			ret, err = h.BinOpShr(vm, right)
			handled = true
		}
	case token.AndNot:
		if h, ok := left.(ObjectWithAndNotBinOperator); ok {
			ret, err = h.BinOpAndNot(vm, right)
			handled = true
		}
	case token.LAnd:
		if h, ok := left.(ObjectWithLAndBinOperator); ok {
			ret, err = h.BinOpLAnd(vm, right)
			handled = true
		}
	case token.Equal:
		if h, ok := left.(ObjectWithEqualBinOperator); ok {
			ret, err = h.BinOpEqual(vm, right)
			handled = true
		}
	case token.NotEqual:
		if h, ok := left.(ObjectWithNotEqualBinOperator); ok {
			ret, err = h.BinOpNotEqual(vm, right)
			handled = true
		}
	case token.Less:
		if h, ok := left.(ObjectWithLessBinOperator); ok {
			ret, err = h.BinOpLess(vm, right)
			handled = true
		}
	case token.Greater:
		if h, ok := left.(ObjectWithGreaterBinOperator); ok {
			ret, err = h.BinOpGreater(vm, right)
			handled = true
		}
	case token.LessEq:
		if h, ok := left.(ObjectWithLessEqBinOperator); ok {
			ret, err = h.BinOpLessEq(vm, right)
			handled = true
		}
	case token.GreaterEq:
		if h, ok := left.(ObjectWithGreaterEqBinOperator); ok {
			ret, err = h.BinOpGreaterEq(vm, right)
			handled = true
		}
	case token.Tilde:
		if h, ok := left.(ObjectWithTildeBinOperator); ok {
			ret, err = h.BinOpTilde(vm, right)
			handled = true
		}
	case token.DoubleTilde:
		if h, ok := left.(ObjectWithDoubleTildeBinOperator); ok {
			ret, err = h.BinOpDoubleTilde(vm, right)
			handled = true
		}
	case token.TripleTilde:
		if h, ok := left.(ObjectWithTripleTildeBinOperator); ok {
			ret, err = h.BinOpTripleTilde(vm, right)
			handled = true
		}
	case token.DotDot:
		if h, ok := left.(ObjectWithDotDotBinOperator); ok {
			ret, err = h.BinOpDotDot(vm, right)
			handled = true
		}
	case token.TripleLess:
		if h, ok := left.(ObjectWithTripleLessBinOperator); ok {
			ret, err = h.BinOpTripleLess(vm, right)
			handled = true
		}
	case token.TripleGreater:
		if h, ok := left.(ObjectWithTripleGreaterBinOperator); ok {
			ret, err = h.BinOpTripleGreater(vm, right)
			handled = true
		}
	case token.DoubleMod:
		if h, ok := left.(ObjectWithDoubleModBinOperator); ok {
			ret, err = h.BinOpDoubleMod(vm, right)
			handled = true
		}
	case token.Lambda:
		if h, ok := left.(ObjectWithLambdaBinOperator); ok {
			ret, err = h.BinOpLambda(vm, right)
			handled = true
		}
	case token.Same:
		if h, ok := left.(ObjectWithSameBinOperator); ok {
			ret, err = h.BinOpSame(vm, right)
			handled = true
		}
	case token.NotSame:
		if h, ok := left.(ObjectWithNotSameBinOperator); ok {
			ret, err = h.BinOpNotSame(vm, right)
			handled = true
		}
	case token.Inc:
		if h, ok := left.(ObjectWithIncBinOperator); ok {
			ret, err = h.BinOpInc(vm, right)
			handled = true
		}
	case token.Dec:
		if h, ok := left.(ObjectWithDecBinOperator); ok {
			ret, err = h.BinOpDec(vm, right)
			handled = true
		}
	case token.In:
		if h, ok := right.(ObjectWithInBinOperator); ok {
			ret, err = h.BinOpIn(vm, left)
			handled = true
		}
	case token.Ain:
		if h, ok := right.(ObjectWithAinBinOperator); ok {
			ret, err = h.BinOpAin(vm, left)
			handled = true
		}
	}
	return
}

// ObjectWithNotUnaryOperator is implemented by an object that handles the
// `!` unary operator.
type ObjectWithNotUnaryOperator interface {
	UnOpNot(vm *VM) (Object, error)
}

// ObjectWithSubUnaryOperator is implemented by an object that handles the
// `-` unary operator.
type ObjectWithSubUnaryOperator interface {
	UnOpSub(vm *VM) (Object, error)
}

// ObjectWithAddUnaryOperator is implemented by an object that handles the
// `+` unary operator.
type ObjectWithAddUnaryOperator interface {
	UnOpAdd(vm *VM) (Object, error)
}

// ObjectWithXorUnaryOperator is implemented by an object that handles the
// `^` unary operator.
type ObjectWithXorUnaryOperator interface {
	UnOpXor(vm *VM) (Object, error)
}

// ObjectWithIncUnaryOperator is implemented by an object that handles the
// `++` unary operator.
type ObjectWithIncUnaryOperator interface {
	UnOpInc(vm *VM) (Object, error)
}

// ObjectWithDecUnaryOperator is implemented by an object that handles the
// `--` unary operator.
type ObjectWithDecUnaryOperator interface {
	UnOpDec(vm *VM) (Object, error)
}

// unOpObject dispatches a unary operator to the operand's typed
// ObjectWith{Op}UnaryOperator implementation. handled is false when operand
// does not implement the operator's interface.
func unOpObject(vm *VM, op UnaryOperatorType, operand Object) (ret Object, err error, handled bool) {
	switch op.Token() {
	case token.Not:
		if h, ok := operand.(ObjectWithNotUnaryOperator); ok {
			ret, err = h.UnOpNot(vm)
			handled = true
		}
	case token.Sub:
		if h, ok := operand.(ObjectWithSubUnaryOperator); ok {
			ret, err = h.UnOpSub(vm)
			handled = true
		}
	case token.Add:
		if h, ok := operand.(ObjectWithAddUnaryOperator); ok {
			ret, err = h.UnOpAdd(vm)
			handled = true
		}
	case token.Xor:
		if h, ok := operand.(ObjectWithXorUnaryOperator); ok {
			ret, err = h.UnOpXor(vm)
			handled = true
		}
	case token.Inc:
		if h, ok := operand.(ObjectWithIncUnaryOperator); ok {
			ret, err = h.UnOpInc(vm)
			handled = true
		}
	case token.Dec:
		if h, ok := operand.(ObjectWithDecUnaryOperator); ok {
			ret, err = h.UnOpDec(vm)
			handled = true
		}
	}
	return
}

// ObjectWithAddSelfAssignOperator is implemented by an object that handles
// the `+=` self-assign operator as the left operand.
type ObjectWithAddSelfAssignOperator interface {
	SelfAssignOpAdd(vm *VM, value Object) (Object, error)
}

// ObjectWithIncSelfAssignOperator is implemented by an object that handles
// the `++=` self-assign operator as the left operand.
type ObjectWithIncSelfAssignOperator interface {
	SelfAssignOpInc(vm *VM, value Object) (Object, error)
}

// ObjectWithSubSelfAssignOperator is implemented by an object that handles
// the `-=` self-assign operator as the left operand.
type ObjectWithSubSelfAssignOperator interface {
	SelfAssignOpSub(vm *VM, value Object) (Object, error)
}

// ObjectWithDecSelfAssignOperator is implemented by an object that handles
// the `--=` self-assign operator as the left operand.
type ObjectWithDecSelfAssignOperator interface {
	SelfAssignOpDec(vm *VM, value Object) (Object, error)
}

// ObjectWithMulSelfAssignOperator is implemented by an object that handles
// the `*=` self-assign operator as the left operand.
type ObjectWithMulSelfAssignOperator interface {
	SelfAssignOpMul(vm *VM, value Object) (Object, error)
}

// ObjectWithPowSelfAssignOperator is implemented by an object that handles
// the `**=` self-assign operator as the left operand.
type ObjectWithPowSelfAssignOperator interface {
	SelfAssignOpPow(vm *VM, value Object) (Object, error)
}

// ObjectWithQuoSelfAssignOperator is implemented by an object that handles
// the `/=` self-assign operator as the left operand.
type ObjectWithQuoSelfAssignOperator interface {
	SelfAssignOpQuo(vm *VM, value Object) (Object, error)
}

// ObjectWithRemSelfAssignOperator is implemented by an object that handles
// the `%=` self-assign operator as the left operand.
type ObjectWithRemSelfAssignOperator interface {
	SelfAssignOpRem(vm *VM, value Object) (Object, error)
}

// ObjectWithAndSelfAssignOperator is implemented by an object that handles
// the `&=` self-assign operator as the left operand.
type ObjectWithAndSelfAssignOperator interface {
	SelfAssignOpAnd(vm *VM, value Object) (Object, error)
}

// ObjectWithOrSelfAssignOperator is implemented by an object that handles
// the `|=` self-assign operator as the left operand.
type ObjectWithOrSelfAssignOperator interface {
	SelfAssignOpOr(vm *VM, value Object) (Object, error)
}

// ObjectWithXorSelfAssignOperator is implemented by an object that handles
// the `^=` self-assign operator as the left operand.
type ObjectWithXorSelfAssignOperator interface {
	SelfAssignOpXor(vm *VM, value Object) (Object, error)
}

// ObjectWithShlSelfAssignOperator is implemented by an object that handles
// the `<<=` self-assign operator as the left operand.
type ObjectWithShlSelfAssignOperator interface {
	SelfAssignOpShl(vm *VM, value Object) (Object, error)
}

// ObjectWithShrSelfAssignOperator is implemented by an object that handles
// the `>>=` self-assign operator as the left operand.
type ObjectWithShrSelfAssignOperator interface {
	SelfAssignOpShr(vm *VM, value Object) (Object, error)
}

// ObjectWithTripleLessSelfAssignOperator is implemented by an object that handles
// the `<<<=` self-assign operator as the left operand.
type ObjectWithTripleLessSelfAssignOperator interface {
	SelfAssignOpTripleLess(vm *VM, value Object) (Object, error)
}

// ObjectWithTripleGreaterSelfAssignOperator is implemented by an object that handles
// the `>>>=` self-assign operator as the left operand.
type ObjectWithTripleGreaterSelfAssignOperator interface {
	SelfAssignOpTripleGreater(vm *VM, value Object) (Object, error)
}

// ObjectWithDoubleModSelfAssignOperator is implemented by an object that handles
// the `%%=` self-assign operator as the left operand.
type ObjectWithDoubleModSelfAssignOperator interface {
	SelfAssignOpDoubleMod(vm *VM, value Object) (Object, error)
}

// ObjectWithAndNotSelfAssignOperator is implemented by an object that handles
// the `&^=` self-assign operator as the left operand.
type ObjectWithAndNotSelfAssignOperator interface {
	SelfAssignOpAndNot(vm *VM, value Object) (Object, error)
}

// ObjectWithLOrSelfAssignOperator is implemented by an object that handles
// the `||=` self-assign operator as the left operand.
type ObjectWithLOrSelfAssignOperator interface {
	SelfAssignOpLOr(vm *VM, value Object) (Object, error)
}

// selfAssignOpObject dispatches a self-assign operator to left's typed
// ObjectWith{Op}SelfAssignOperator implementation. handled is false when left
// does not implement the operator's interface.
func selfAssignOpObject(vm *VM, op SelfAssignOperatorType, left, value Object) (ret Object, err error, handled bool) {
	switch op.Token() {
	case token.Add:
		if h, ok := left.(ObjectWithAddSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpAdd(vm, value)
			handled = true
		}
	case token.Inc:
		if h, ok := left.(ObjectWithIncSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpInc(vm, value)
			handled = true
		}
	case token.Sub:
		if h, ok := left.(ObjectWithSubSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpSub(vm, value)
			handled = true
		}
	case token.Dec:
		if h, ok := left.(ObjectWithDecSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpDec(vm, value)
			handled = true
		}
	case token.Mul:
		if h, ok := left.(ObjectWithMulSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpMul(vm, value)
			handled = true
		}
	case token.Pow:
		if h, ok := left.(ObjectWithPowSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpPow(vm, value)
			handled = true
		}
	case token.Quo:
		if h, ok := left.(ObjectWithQuoSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpQuo(vm, value)
			handled = true
		}
	case token.Rem:
		if h, ok := left.(ObjectWithRemSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpRem(vm, value)
			handled = true
		}
	case token.And:
		if h, ok := left.(ObjectWithAndSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpAnd(vm, value)
			handled = true
		}
	case token.Or:
		if h, ok := left.(ObjectWithOrSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpOr(vm, value)
			handled = true
		}
	case token.Xor:
		if h, ok := left.(ObjectWithXorSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpXor(vm, value)
			handled = true
		}
	case token.Shl:
		if h, ok := left.(ObjectWithShlSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpShl(vm, value)
			handled = true
		}
	case token.Shr:
		if h, ok := left.(ObjectWithShrSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpShr(vm, value)
			handled = true
		}
	case token.TripleLess:
		if h, ok := left.(ObjectWithTripleLessSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpTripleLess(vm, value)
			handled = true
		}
	case token.TripleGreater:
		if h, ok := left.(ObjectWithTripleGreaterSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpTripleGreater(vm, value)
			handled = true
		}
	case token.DoubleMod:
		if h, ok := left.(ObjectWithDoubleModSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpDoubleMod(vm, value)
			handled = true
		}
	case token.AndNot:
		if h, ok := left.(ObjectWithAndNotSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpAndNot(vm, value)
			handled = true
		}
	case token.LOr:
		if h, ok := left.(ObjectWithLOrSelfAssignOperator); ok {
			ret, err = h.SelfAssignOpLOr(vm, value)
			handled = true
		}
	}
	return
}
