// Code generated by 'go generate'; DO NOT EDIT.

package stdlib

import (
	"strconv"

	"github.com/gad-lang/gad"
)

// FuncPOROEx is a generated function to make gad.CallableExFunc.
// Source: func(o gad.Object) (ret gad.Object)
func FuncPOROEx(fn func(gad.Object) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		o := args.Get(0)

		ret = fn(o)
		return
	}
}

// FuncPiROEx is a generated function to make gad.CallableExFunc.
// Source: func(i1 int) (ret gad.Object)
func FuncPiROEx(fn func(int) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		i1, ok := gad.ToGoInt(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args.Get(0).TypeName())
		}

		ret = fn(i1)
		return
	}
}

// FuncPi64ROEx is a generated function to make gad.CallableExFunc.
// Source: func(i1 int64) (ret gad.Object)
func FuncPi64ROEx(fn func(int64) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		i1, ok := gad.ToGoInt64(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args.Get(0).TypeName())
		}

		ret = fn(i1)
		return
	}
}

// FuncPi64REx is a generated function to make gad.CallableExFunc.
// Source: func(i1 int64)
func FuncPi64REx(fn func(int64)) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		i1, ok := gad.ToGoInt64(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args.Get(0).TypeName())
		}

		fn(i1)
		ret = gad.Nil
		return
	}
}

// FuncPsROeEx is a generated function to make gad.CallableExFunc.
// Source: func(s string) (ret gad.Object, err error)
func FuncPsROeEx(fn func(string) (gad.Object, error)) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		s, ok := gad.ToGoString(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args.Get(0).TypeName())
		}

		ret, err = fn(s)
		return
	}
}

// FuncPsiROEx is a generated function to make gad.CallableExFunc.
// Source: func(s string, i1 int) (ret gad.Object)
func FuncPsiROEx(fn func(string, int) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		s, ok := gad.ToGoString(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args.Get(0).TypeName())
		}
		i1, ok := gad.ToGoInt(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", args.Get(1).TypeName())
		}

		ret = fn(s, i1)
		return
	}
}

// FuncPROEx is a generated function to make gad.CallableExFunc.
// Source: func() (ret gad.Object)
func FuncPROEx(fn func() gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(0); err != nil {
			return gad.Nil, err
		}

		ret = fn()
		return
	}
}

// FuncPi64i64ROEx is a generated function to make gad.CallableExFunc.
// Source: func(i1 int64, i2 int64) (ret gad.Object)
func FuncPi64i64ROEx(fn func(int64, int64) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		i1, ok := gad.ToGoInt64(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args.Get(0).TypeName())
		}
		i2, ok := gad.ToGoInt64(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", args.Get(1).TypeName())
		}

		ret = fn(i1, i2)
		return
	}
}

// FuncPb2ROEx is a generated function to make gad.CallableExFunc.
// Source: func(b []byte) (ret gad.Object)
func FuncPb2ROEx(fn func([]byte) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		b, ok := gad.ToGoByteSlice(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "bytes", args.Get(0).TypeName())
		}

		ret = fn(b)
		return
	}
}

// FuncPOssROEx is a generated function to make gad.CallableExFunc.
// Source: func(o gad.Object, s1 string, s2 string) (ret gad.Object)
func FuncPOssROEx(fn func(gad.Object, string, string) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(3); err != nil {
			return gad.Nil, err
		}

		o := args.Get(0)
		s1, ok := gad.ToGoString(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args.Get(1).TypeName())
		}
		s2, ok := gad.ToGoString(args.Get(2))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("3rd", "string", args.Get(2).TypeName())
		}

		ret = fn(o, s1, s2)
		return
	}
}

// FuncPb2bROEx is a generated function to make gad.CallableExFunc.
// Source: func(p []byte, b bool) (ret gad.Object)
func FuncPb2bROEx(fn func([]byte, bool) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		p, ok := gad.ToGoByteSlice(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "bytes", args.Get(0).TypeName())
		}
		b, ok := gad.ToGoBool(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "bool", args.Get(1).TypeName())
		}

		ret = fn(p, b)
		return
	}
}

// FuncPb2ssROEx is a generated function to make gad.CallableExFunc.
// Source: func(p []byte, s1 string, s2 string) (ret gad.Object)
func FuncPb2ssROEx(fn func([]byte, string, string) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(3); err != nil {
			return gad.Nil, err
		}

		p, ok := gad.ToGoByteSlice(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "bytes", args.Get(0).TypeName())
		}
		s1, ok := gad.ToGoString(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args.Get(1).TypeName())
		}
		s2, ok := gad.ToGoString(args.Get(2))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("3rd", "string", args.Get(2).TypeName())
		}

		ret = fn(p, s1, s2)
		return
	}
}

// FuncPssROEx is a generated function to make gad.CallableExFunc.
// Source: func(s1 string, s2 string) (ret gad.Object)
func FuncPssROEx(fn func(string, string) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		s1, ok := gad.ToGoString(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args.Get(0).TypeName())
		}
		s2, ok := gad.ToGoString(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args.Get(1).TypeName())
		}

		ret = fn(s1, s2)
		return
	}
}

// FuncPsROEx is a generated function to make gad.CallableExFunc.
// Source: func(s string) (ret gad.Object)
func FuncPsROEx(fn func(string) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return gad.Nil, err
		}

		s, ok := gad.ToGoString(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args.Get(0).TypeName())
		}

		ret = fn(s)
		return
	}
}

// FuncPsrROEx is a generated function to make gad.CallableExFunc.
// Source: func(s string, r rune) (ret gad.Object)
func FuncPsrROEx(fn func(string, rune) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		s, ok := gad.ToGoString(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args.Get(0).TypeName())
		}
		r, ok := gad.ToGoRune(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "char", args.Get(1).TypeName())
		}

		ret = fn(s, r)
		return
	}
}

// FuncPAsROEx is a generated function to make gad.CallableExFunc.
// Source: func(arr gad.Array, s string) (ret gad.Object)
func FuncPAsROEx(fn func(gad.Array, string) gad.Object) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		arr, ok := gad.ToArray(args.Get(0))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "array", args.Get(0).TypeName())
		}
		s, ok := gad.ToGoString(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args.Get(1).TypeName())
		}

		ret = fn(arr, s)
		return
	}
}

// FuncPOi64ROeEx is a generated function to make gad.CallableExFunc.
// Source: func(o gad.Object, i int64) (ret gad.Object, err error)
func FuncPOi64ROeEx(fn func(gad.Object, int64) (gad.Object, error)) gad.CallableExFunc {
	return func(args gad.Call) (ret gad.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return gad.Nil, err
		}

		o := args.Get(0)
		i, ok := gad.ToGoInt64(args.Get(1))
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", args.Get(1).TypeName())
		}

		ret, err = fn(o, i)
		return
	}
}

// FuncPORO is a generated function to make gad.CallableFunc.
// Source: func(o gad.Object) (ret gad.Object)
func FuncPORO(fn func(gad.Object) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 1 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]

		ret = fn(o)
		return
	}
}

// FuncPiRO is a generated function to make gad.CallableFunc.
// Source: func(i1 int) (ret gad.Object)
func FuncPiRO(fn func(int) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 1 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		i1, ok := gad.ToGoInt(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args[0].TypeName())
		}

		ret = fn(i1)
		return
	}
}

// FuncPi64RO is a generated function to make gad.CallableFunc.
// Source: func(i1 int64) (ret gad.Object)
func FuncPi64RO(fn func(int64) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 1 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		i1, ok := gad.ToGoInt64(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args[0].TypeName())
		}

		ret = fn(i1)
		return
	}
}

// FuncPi64R is a generated function to make gad.CallableFunc.
// Source: func(i1 int64)
func FuncPi64R(fn func(int64)) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 1 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		i1, ok := gad.ToGoInt64(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args[0].TypeName())
		}

		fn(i1)
		ret = gad.Nil
		return
	}
}

// FuncPsROe is a generated function to make gad.CallableFunc.
// Source: func(s string) (ret gad.Object, err error)
func FuncPsROe(fn func(string) (gad.Object, error)) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 1 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		s, ok := gad.ToGoString(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args[0].TypeName())
		}

		ret, err = fn(s)
		return
	}
}

// FuncPsiRO is a generated function to make gad.CallableFunc.
// Source: func(s string, i1 int) (ret gad.Object)
func FuncPsiRO(fn func(string, int) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 2 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		s, ok := gad.ToGoString(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args[0].TypeName())
		}
		i1, ok := gad.ToGoInt(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}

		ret = fn(s, i1)
		return
	}
}

// FuncPRO is a generated function to make gad.CallableFunc.
// Source: func() (ret gad.Object)
func FuncPRO(fn func() gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 0 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=0 got=" + strconv.Itoa(len(args)))
		}

		ret = fn()
		return
	}
}

// FuncPi64i64RO is a generated function to make gad.CallableFunc.
// Source: func(i1 int64, i2 int64) (ret gad.Object)
func FuncPi64i64RO(fn func(int64, int64) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 2 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		i1, ok := gad.ToGoInt64(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "int", args[0].TypeName())
		}
		i2, ok := gad.ToGoInt64(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}

		ret = fn(i1, i2)
		return
	}
}

// FuncPb2RO is a generated function to make gad.CallableFunc.
// Source: func(b []byte) (ret gad.Object)
func FuncPb2RO(fn func([]byte) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 1 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		b, ok := gad.ToGoByteSlice(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "bytes", args[0].TypeName())
		}

		ret = fn(b)
		return
	}
}

// FuncPOssRO is a generated function to make gad.CallableFunc.
// Source: func(o gad.Object, s1 string, s2 string) (ret gad.Object)
func FuncPOssRO(fn func(gad.Object, string, string) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 3 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=3 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]
		s1, ok := gad.ToGoString(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args[1].TypeName())
		}
		s2, ok := gad.ToGoString(args[2])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("3rd", "string", args[2].TypeName())
		}

		ret = fn(o, s1, s2)
		return
	}
}

// FuncPb2bRO is a generated function to make gad.CallableFunc.
// Source: func(p []byte, b bool) (ret gad.Object)
func FuncPb2bRO(fn func([]byte, bool) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 2 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		p, ok := gad.ToGoByteSlice(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "bytes", args[0].TypeName())
		}
		b, ok := gad.ToGoBool(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "bool", args[1].TypeName())
		}

		ret = fn(p, b)
		return
	}
}

// FuncPb2ssRO is a generated function to make gad.CallableFunc.
// Source: func(p []byte, s1 string, s2 string) (ret gad.Object)
func FuncPb2ssRO(fn func([]byte, string, string) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 3 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=3 got=" + strconv.Itoa(len(args)))
		}

		p, ok := gad.ToGoByteSlice(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "bytes", args[0].TypeName())
		}
		s1, ok := gad.ToGoString(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args[1].TypeName())
		}
		s2, ok := gad.ToGoString(args[2])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("3rd", "string", args[2].TypeName())
		}

		ret = fn(p, s1, s2)
		return
	}
}

// FuncPssRO is a generated function to make gad.CallableFunc.
// Source: func(s1 string, s2 string) (ret gad.Object)
func FuncPssRO(fn func(string, string) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 2 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		s1, ok := gad.ToGoString(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args[0].TypeName())
		}
		s2, ok := gad.ToGoString(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args[1].TypeName())
		}

		ret = fn(s1, s2)
		return
	}
}

// FuncPsRO is a generated function to make gad.CallableFunc.
// Source: func(s string) (ret gad.Object)
func FuncPsRO(fn func(string) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 1 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		s, ok := gad.ToGoString(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args[0].TypeName())
		}

		ret = fn(s)
		return
	}
}

// FuncPsrRO is a generated function to make gad.CallableFunc.
// Source: func(s string, r rune) (ret gad.Object)
func FuncPsrRO(fn func(string, rune) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 2 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		s, ok := gad.ToGoString(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "string", args[0].TypeName())
		}
		r, ok := gad.ToGoRune(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "char", args[1].TypeName())
		}

		ret = fn(s, r)
		return
	}
}

// FuncPAsRO is a generated function to make gad.CallableFunc.
// Source: func(arr gad.Array, s string) (ret gad.Object)
func FuncPAsRO(fn func(gad.Array, string) gad.Object) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 2 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		arr, ok := gad.ToArray(args[0])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("1st", "array", args[0].TypeName())
		}
		s, ok := gad.ToGoString(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "string", args[1].TypeName())
		}

		ret = fn(arr, s)
		return
	}
}

// FuncPOi64ROe is a generated function to make gad.CallableFunc.
// Source: func(o gad.Object, i int64) (ret gad.Object, err error)
func FuncPOi64ROe(fn func(gad.Object, int64) (gad.Object, error)) gad.CallableFunc {
	return func(args ...gad.Object) (ret gad.Object, err error) {
		if len(args) != 2 {
			return gad.Nil, gad.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]
		i, ok := gad.ToGoInt64(args[1])
		if !ok {
			return gad.Nil, gad.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}

		ret, err = fn(o, i)
		return
	}
}
