// Command update-delve keeps the VM's debug execution loop (vm_loop_debug.go)
// in sync with the production loop (vm_loop.go). The debug loop is a generated
// copy of VM.loop with a per-instruction debugger hook injected, so the two
// never drift while the production loop keeps no hook of its own.
//
// Usage:
//
//	go run ./cmd/update-delve gen      # (re)generate vm_loop_debug.go
//	go run ./cmd/update-delve check    # fail if it is out of date (CI)
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"

	cc "github.com/moisespsena-go/command-context"
)

const (
	defaultSrc = "vm_loop.go"
	defaultOut = "vm_loop_debug.go"

	srcMarker = "func (vm *VM) loop() {"
	dstMarker = "func (vm *VM) loopDebug() {"
	// anchor is the instruction-fetch line; the debugger hook is injected right
	// after it (the VM is then positioned at the instruction about to run).
	anchor = "\t\top = Opcode(vm.curInsts[vm.ip])\n"
	hook   = "\t\tvm.dbg.Step(vm)\n"
)

func main() {
	root := &cc.Command{
		Name:        "update-delve",
		Description: "Keep vm_loop_debug.go (the VM debug loop) in sync with vm_loop.go.",
		Run: func(ctx *cc.CommandContext) error {
			return ctx.Help()
		},
	}
	root.Sub(genCommand())
	root.Sub(checkCommand())

	ctx, err := root.Parse(nil)
	if err != nil {
		fmt.Fprintln(os.Stderr, "ERROR:", err)
		os.Exit(1)
	}
	if err = ctx.Run(); err != nil {
		fmt.Fprintln(os.Stderr, "ERROR:", err)
		os.Exit(1)
	}
}

func srcOutFlags(ctx *cc.CommandContext) (src, out *string) {
	src = ctx.Flags().String("src", defaultSrc, "production VM loop source file")
	out = ctx.Flags().String("out", defaultOut, "generated debug VM loop file")
	return
}

func genCommand() *cc.Command {
	var src, out *string
	return &cc.Command{
		Name:        "gen",
		Usage:       "[flags]",
		Description: "Generate the debug VM loop from the production loop.",
		New: func(ctx *cc.CommandContext) error {
			src, out = srcOutFlags(ctx)
			return nil
		},
		Run: func(ctx *cc.CommandContext) error {
			generated, err := generateFrom(*src)
			if err != nil {
				return err
			}
			existing, _ := os.ReadFile(*out)
			if bytes.Equal(existing, generated) {
				fmt.Fprintf(ctx.Out, "%s already up to date\n", *out)
				return nil
			}
			if err = os.WriteFile(*out, generated, 0o644); err != nil {
				return err
			}
			fmt.Fprintf(ctx.Out, "wrote %s from %s\n", *out, *src)
			return nil
		},
	}
}

func checkCommand() *cc.Command {
	var src, out *string
	return &cc.Command{
		Name:        "check",
		Usage:       "[flags]",
		Description: "Verify the debug VM loop is up to date; exit non-zero otherwise.",
		New: func(ctx *cc.CommandContext) error {
			src, out = srcOutFlags(ctx)
			return nil
		},
		Run: func(ctx *cc.CommandContext) error {
			generated, err := generateFrom(*src)
			if err != nil {
				return err
			}
			existing, err := os.ReadFile(*out)
			if err != nil {
				return fmt.Errorf("%s missing: run `go run ./cmd/update-delve gen`", *out)
			}
			if !bytes.Equal(existing, generated) {
				fmt.Fprintf(ctx.Err, "%s is out of date: run `go run ./cmd/update-delve gen`\n", *out)
				os.Exit(2)
			}
			fmt.Fprintf(ctx.Out, "%s is up to date\n", *out)
			return nil
		},
	}
}

// generateFrom reads the production loop file and returns the formatted debug
// loop source.
func generateFrom(srcPath string) ([]byte, error) {
	data, err := os.ReadFile(srcPath)
	if err != nil {
		return nil, err
	}
	return generate(data)
}

// generate transforms the production loop source into the debug loop: it renames
// VM.loop to VM.loopDebug and injects the per-instruction debugger hook.
func generate(src []byte) ([]byte, error) {
	s := string(src)
	if !strings.Contains(s, srcMarker) {
		return nil, fmt.Errorf("could not find %q in source", srcMarker)
	}
	if n := strings.Count(s, anchor); n != 1 {
		return nil, fmt.Errorf("expected exactly one instruction-fetch anchor, found %d", n)
	}

	s = strings.Replace(s, srcMarker, dstMarker, 1)
	s = strings.Replace(s, anchor, anchor+hook, 1)

	header := strings.Join([]string{
		"// Code generated by cmd/update-delve; DO NOT EDIT.",
		"//",
		"// loopDebug mirrors VM.loop (vm_loop.go) with a per-instruction debugger",
		"// hook. Regenerate after editing vm_loop.go with:",
		"//",
		"//\tgo run ./cmd/update-delve gen",
		"", "",
	}, "\n")

	return format.Source([]byte(header + s))
}
