fmt:
    no-array-item-in-new-line: true
    no-call-params-in-new-line: true
    no-dict-item-in-new-line: true
ide:
    breakpoints:
        01_hello.gad:
            - 4
            - 12
    outputHeight: 200
    run:
        01_hello.gad:
            args: []
            disabled: []
            safe: false
            saveOut: ""
    sidebarWidth: 240
    theme: dark
