package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/gad-lang/gad/token"
)

const (
	builtinBinaryPrefix = "BuiltinBinaryOperator"
	tBinaryPrefix       = "TBinaryOperator"

	builtinSelfAssignPrefix = "BuiltinSelfAssignOperator"
	tSelfAssignPrefix       = "TSelfAssignOperator"

	builtinUnaryPrefix = "BuiltinUnaryOperator"
	tUnaryPrefix       = "TUnaryOperator"
)

func main() {
	binaryOperators := listGroup(token.GroupBinaryOperatorBegin, token.GroupBinaryOperatorEnd)
	// `++` and `--` are usable as binary operators too (they live in the
	// self-assign token group, so add them explicitly). `in` is the membership
	// operator (a keyword, not in the operator token group); it is added so it
	// gets a TBinaryOperatorIn type and an ObjectWithInBinOperator interface,
	// and is user-overridable via `met core.binOp(_ TBinaryOperatorIn, …)`.
	// `ain` is the array-membership operator (`A ain B`): like `in`, it is a
	// keyword dispatched on the right operand (the container), so it gets a
	// TBinaryOperatorAin type and an ObjectWithAinBinOperator interface.
	binaryOperators = append(binaryOperators, token.Inc, token.Dec, token.In, token.Ain)
	selfAssignOperators := listGroup(token.GroupSelfAssignOperatorBegin, token.NullichAssign)
	for i, op := range selfAssignOperators {
		selfAssignOperators[i] = token.Unassign(op)
	}
	// Unary operators are an explicit list: `!`, `-`, `+`, `^` are binary-group
	// tokens reused as unary, while `++`/`--` live in the unary token group. Each
	// gets a TUnaryOperator type and an ObjectWith{Op}UnaryOperator interface, and
	// is user-overridable via `met core.unOp(_ TUnaryOperator{Op}, …)`.
	unaryOperators := []token.Token{
		token.Not, token.Sub, token.Add, token.Xor, token.Inc, token.Dec,
	}

	var f strings.Builder
	f.WriteString("// Code generated by 'go generate'; DO NOT EDIT.\n")
	f.WriteString("package gad\n")
	f.WriteString("import \"github.com/gad-lang/gad/token\"\n")
	f.WriteString("var (\n")
	for _, o := range binaryOperators {
		fmt.Fprintf(&f, "%s%s = BinaryOperatorType(token.%[2]s) // %s\n", tBinaryPrefix, o.Name(), o.String())
	}
	f.WriteString("\n")
	for _, o := range selfAssignOperators {
		fmt.Fprintf(&f, "%s%s = SelfAssignOperatorType(token.%[2]s) // %s\n", tSelfAssignPrefix, o.Name(), o.String())
	}
	f.WriteString("\n")
	for _, o := range unaryOperators {
		fmt.Fprintf(&f, "%s%s = UnaryOperatorType(token.%[2]s) // %s\n", tUnaryPrefix, o.Name(), o.String())
	}
	f.WriteString(")\n")
	f.WriteString("func init () {\n")

	f.WriteString("add := func(bt BuiltinType, t ObjectType) {\n" +
		"BuiltinObjects[bt] = t\n" +
		"BuiltinsMap[t.Name()] = bt\n" +
		"}\n")
	for _, o := range binaryOperators {
		fmt.Fprintf(&f, "add(%[1]s%[3]s, %[2]s%[3]s)\n", builtinBinaryPrefix, tBinaryPrefix, o.Name())
	}
	f.WriteString("\n")
	for _, o := range selfAssignOperators {
		fmt.Fprintf(&f, "add(%[1]s%[3]s, %[2]s%[3]s)\n", builtinSelfAssignPrefix, tSelfAssignPrefix, o.Name())
	}
	f.WriteString("\n")
	for _, o := range unaryOperators {
		fmt.Fprintf(&f, "add(%[1]s%[3]s, %[2]s%[3]s)\n", builtinUnaryPrefix, tUnaryPrefix, o.Name())
	}
	f.WriteString("}\n")

	outName := "builtin_operators.go"

	if err := os.WriteFile("builtin_operators.go", []byte(f.String()), 0666); err != nil {
		panic(err)
	}

	err := exec.Command("go", "fmt", outName).Run()
	if err != nil {
		panic(err)
	}

	builtins, err := os.ReadFile("builtins.go")
	if err != nil {
		panic(err)
	}

	builtins = appendBuiltins(builtins, builtinBinaryPrefix, binaryOperators)
	builtins = appendBuiltins(builtins, builtinSelfAssignPrefix, selfAssignOperators)
	builtins = appendBuiltins(builtins, builtinUnaryPrefix, unaryOperators)

	if err := os.WriteFile("builtins.go", builtins, 0666); err != nil {
		panic(err)
	}

	if err := exec.Command("go", "fmt", "builtins.go").Run(); err != nil {
		panic(err)
	}

	writeOpAPI(binaryOperators, unaryOperators, selfAssignOperators)
}

// writeOpAPI generates op_api.go: one interface per binary operator
// (ObjectWith{Op}BinOperator with a BinOp{Op}(vm, right) method) plus a
// dispatcher that routes an operator to the left operand's typed implementation.
func writeOpAPI(binaryOperators, unaryOperators, selfAssignOperators []token.Token) {
	var f strings.Builder
	f.WriteString("// Code generated by 'go generate'; DO NOT EDIT.\n\n")
	f.WriteString("package gad\n\n")
	f.WriteString("import \"github.com/gad-lang/gad/token\"\n\n")

	for _, o := range binaryOperators {
		fmt.Fprintf(&f,
			"// ObjectWith%sBinOperator is implemented by an object that handles the `%s`\n"+
				"// binary operator as the left operand.\n"+
				"type ObjectWith%[1]sBinOperator interface {\n"+
				"\tBinOp%[1]s(vm *VM, right Object) (Object, error)\n}\n\n",
			o.Name(), o.String())
	}

	f.WriteString("// binOpObject dispatches a binary operator to left's typed\n")
	f.WriteString("// ObjectWith{Op}BinOperator implementation. handled is false when left does\n")
	f.WriteString("// not implement the operator's interface.\n")
	f.WriteString("func binOpObject(vm *VM, op BinaryOperatorType, left, right Object) (ret Object, err error, handled bool) {\n")
	f.WriteString("\tswitch op.Token() {\n")
	for _, o := range binaryOperators {
		if o == token.In || o == token.Ain {
			// `a in b` / `A ain b` test membership in b, so the implementing
			// object is the right operand (the container) and the value(s) are
			// passed as arg.
			fmt.Fprintf(&f,
				"\tcase token.%s:\n"+
					"\t\tif h, ok := right.(ObjectWith%[2]sBinOperator); ok {\n"+
					"\t\t\tret, err = h.BinOp%[2]s(vm, left)\n"+
					"\t\t\thandled = true\n\t\t}\n",
				o.Name(), o.Name())
			continue
		}
		fmt.Fprintf(&f,
			"\tcase token.%s:\n"+
				"\t\tif h, ok := left.(ObjectWith%[2]sBinOperator); ok {\n"+
				"\t\t\tret, err = h.BinOp%[2]s(vm, right)\n"+
				"\t\t\thandled = true\n\t\t}\n",
			o.Name(), o.Name())
	}
	f.WriteString("\t}\n\treturn\n}\n\n")

	for _, o := range unaryOperators {
		fmt.Fprintf(&f,
			"// ObjectWith%sUnaryOperator is implemented by an object that handles the\n"+
				"// `%s` unary operator.\n"+
				"type ObjectWith%[1]sUnaryOperator interface {\n"+
				"\tUnOp%[1]s(vm *VM) (Object, error)\n}\n\n",
			o.Name(), o.String())
	}

	f.WriteString("// unOpObject dispatches a unary operator to the operand's typed\n")
	f.WriteString("// ObjectWith{Op}UnaryOperator implementation. handled is false when operand\n")
	f.WriteString("// does not implement the operator's interface.\n")
	f.WriteString("func unOpObject(vm *VM, op UnaryOperatorType, operand Object) (ret Object, err error, handled bool) {\n")
	f.WriteString("\tswitch op.Token() {\n")
	for _, o := range unaryOperators {
		fmt.Fprintf(&f,
			"\tcase token.%s:\n"+
				"\t\tif h, ok := operand.(ObjectWith%[2]sUnaryOperator); ok {\n"+
				"\t\t\tret, err = h.UnOp%[2]s(vm)\n"+
				"\t\t\thandled = true\n\t\t}\n",
			o.Name(), o.Name())
	}
	f.WriteString("\t}\n\treturn\n}\n\n")

	for _, o := range selfAssignOperators {
		fmt.Fprintf(&f,
			"// ObjectWith%sSelfAssignOperator is implemented by an object that handles\n"+
				"// the `%s=` self-assign operator as the left operand.\n"+
				"type ObjectWith%[1]sSelfAssignOperator interface {\n"+
				"\tSelfAssignOp%[1]s(vm *VM, value Object) (Object, error)\n}\n\n",
			o.Name(), o.String())
	}

	f.WriteString("// selfAssignOpObject dispatches a self-assign operator to left's typed\n")
	f.WriteString("// ObjectWith{Op}SelfAssignOperator implementation. handled is false when left\n")
	f.WriteString("// does not implement the operator's interface.\n")
	f.WriteString("func selfAssignOpObject(vm *VM, op SelfAssignOperatorType, left, value Object) (ret Object, err error, handled bool) {\n")
	f.WriteString("\tswitch op.Token() {\n")
	for _, o := range selfAssignOperators {
		fmt.Fprintf(&f,
			"\tcase token.%s:\n"+
				"\t\tif h, ok := left.(ObjectWith%[2]sSelfAssignOperator); ok {\n"+
				"\t\t\tret, err = h.SelfAssignOp%[2]s(vm, value)\n"+
				"\t\t\thandled = true\n\t\t}\n",
			o.Name(), o.Name())
	}
	f.WriteString("\t}\n\treturn\n}\n")

	if err := os.WriteFile("op_api.go", []byte(f.String()), 0666); err != nil {
		panic(err)
	}
	if err := exec.Command("go", "fmt", "op_api.go").Run(); err != nil {
		panic(err)
	}
}

func listGroup(groupStart, groupEnd token.Token) (r []token.Token) {
	r = make([]token.Token, groupEnd-groupStart-1)
	for t := groupStart + 1; t < groupEnd; t++ {
		r[t-groupStart-1] = t
	}
	return
}

func appendBuiltins(data []byte, prefix string, tokens []token.Token) []byte {
	var (
		name      = "Group" + prefix + "s"
		startName = []byte(name + "Begin")
		endName   = []byte(name + "End")
		start     = bytes.Index(data, startName)
	)
	if start == -1 {
		panic("bad name " + name + "Begin_")
	}

	end := bytes.Index(data, endName)
	if end == -1 {
		panic("bad name " + name + "End_")
	}

	var buf bytes.Buffer
	buf.Write(bytes.TrimSpace(data[:start]))
	buf.WriteString("\n\n")
	buf.Write(startName)
	buf.WriteByte('\n')

	for _, t := range tokens {
		buf.WriteString(prefix)
		buf.WriteString(t.Name())
		buf.WriteByte('\n')
	}

	buf.Write(endName)
	buf.WriteString("\n\n")

	buf.Write(bytes.TrimSpace(data[end+len(endName):]))
	return buf.Bytes()
}
