package main

import (
	"fmt"
	"html/template"
	"io"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// siteConfig carries build-time site metadata: the repository link and the
// release info (tag, name, notes) surfaced in the header banner and the Download
// page.
type siteConfig struct {
	RepoURL      string // e.g. https://github.com/gad-lang/gad
	ReleaseTag   string // e.g. v1.2.3 (empty for a plain commit build)
	ReleaseName  string // display name (defaults to the tag)
	ReleaseNotes string // release notes as Markdown
	ReleaseDate  string // display date next to the name
	BuildWASM    bool

	// playHref is the site-root-relative path of the Playground/demo, set during
	// the build (not a flag) for the header link.
	playHref string
	// prism is set when the PrismJS bundle was built (loads prism.js + enables
	// syntax highlighting).
	prism bool
	// commit is the git commit the site is built from, used for "view source on
	// GitHub" links; set during the build (git rev-parse), falls back to "main".
	commit string
}

// gitCommit returns the HEAD commit of repoRoot for source links, or "main" when
// it cannot be determined (not a git checkout, git missing, …).
func gitCommit(repoRoot string) string {
	out, err := exec.Command("git", "-C", repoRoot, "rev-parse", "HEAD").Output()
	if s := strings.TrimSpace(string(out)); err == nil && s != "" {
		return s
	}
	return "main"
}

// releaseName returns the display name for the release banner (name, else tag).
func (c siteConfig) releaseName() string {
	if c.ReleaseName != "" {
		return c.ReleaseName
	}
	return c.ReleaseTag
}

// hasRelease reports whether a tagged release is known (banner + asset links).
func (c siteConfig) hasRelease() bool { return c.ReleaseTag != "" }

// releaseURL is the GitHub release page (specific tag, or /latest).
func (c siteConfig) releaseURL() string {
	if c.hasRelease() {
		return c.RepoURL + "/releases/tag/" + c.ReleaseTag
	}
	return c.RepoURL + "/releases/latest"
}

// assetURL returns the download URL of a release asset for the known tag; when
// no tag is known it points at the latest release's asset by name.
func (c siteConfig) assetURL(name string) string {
	if c.hasRelease() {
		return c.RepoURL + "/releases/download/" + c.ReleaseTag + "/" + name
	}
	return c.RepoURL + "/releases/latest/download/" + name
}

// page is one rendered documentation page.
type page struct {
	Slug     string
	Title    string
	OutFile  string
	Section  string
	BodyHTML template.HTML
	Headings []Heading
	// plain is the searchable plain text of the page.
	plain string
	// Source is the sample source file backing a generated chapter page, with
	// SourceLang its PrismJS highlight language ("gad", "gadt" or "gadx") and
	// SourcePath its repo-relative path (for a GitHub link); empty for pages
	// without a backing source.
	Source     string
	SourceLang string
	SourcePath string
}

// navGroup is a sidebar section.
type navGroup struct {
	Name  string
	Pages []*page
}

// guideOrder / refOrder give the curated nav ordering (filenames without .md).
// The language chapters now live in samples/ and are published from doc/samples
// as the "Language" section (see langOrder / collectLangPages).
// The guide leads with getting-started ("Get Started"), which is also the Docs
// landing page (the SPA redirects /docs to the first page of the first group).
// The old doc/README.md "Gad Language" index page is intentionally not published.
var guideOrder = []string{
	"getting-started", "builtins", "formatting", "embedding",
}

var refOrder = []string{
	"tutorial", "workspace-config", "conventions",
}

// stdlibOrder curates the "Standard Library" nav submenu — one page per module,
// sourced from doc/stdlib/<module>.md. The four namespace modules
// (strings/fmt/json/time) are generated by gaddoc; `test` is hand-written.
var stdlibOrder = []string{
	"strings", "fmt", "json", "time", "base64", "test",
}

// langOrder is the curated nav ordering for the language chapters generated from
// the samples into doc/samples (filenames without .md). Any doc/samples page not
// listed here is appended after, sorted by name, so nothing is dropped.
var langOrder = []string{
	"README",
	"02_values_and_types", "33_variables_and_scopes",
	"14_user_operators", "13_ranges", "15_in_operator", "17_unary_operators", "28_absent_coalescing",
	"06_control_flow", "18_with",
	"03_functions", "10_functions_with_methods", "31_properties",
	"04_collections", "05_comprehensions", "22_key_value_array", "27_destructuring",
	"class/classes", "class/syntax", "class/field_types", "class/field_defaults_test",
	"12_method_interfaces", "24_interfaces", "35_type_unions", "36_type_parameters", "20_enum",
	"08_strings_bytes_regex", "21_heredocs", "07_error_handling",
	"26_embed", "09_template", "23_template",
	"16_doc_comments", "29_special_keywords", "34_metaprogramming",
}

// gadxOrder is the curated nav ordering for the Gadx template docs, sourced from
// the ./gadx submodule's docs directory. Pages are emitted with a `gadx-` prefix
// so they never collide with the Gad guide/reference pages.
var gadxOrder = []string{
	"getting-started", "syntax", "components-and-slots", "examples",
	"embedding", "serving-http", "api", "conventions", "source-positions",
	"project-structure", "benchmarks", "cms-example",
}

// buildSite renders the whole website into outDir.
func buildSite(repoRoot, outDir string, cfg siteConfig) error {
	buildWASM := cfg.BuildWASM
	cfg.commit = gitCommit(repoRoot)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	guide, err := collectPages(filepath.Join(repoRoot, "doc"), guideOrder, "Guide", true)
	if err != nil {
		return err
	}
	ref, err := collectPages(filepath.Join(repoRoot, "doc"), refOrder, "Reference", false)
	if err != nil {
		return err
	}
	stdlib, err := collectStdlibPages(filepath.Join(repoRoot, "doc", "stdlib"), stdlibOrder)
	if err != nil {
		return err
	}
	// reflect is a standard-library module too, but its page is hand-written at
	// doc/reflect.md (keeping the stable `ref-reflect` route); group it with the
	// rest under "Standard Library".
	reflectPages, err := collectPages(filepath.Join(repoRoot, "doc"), []string{"reflect"}, "Standard Library", false)
	if err != nil {
		return err
	}
	stdlib = append(stdlib, reflectPages...)

	// Language chapters generated from the samples into doc/samples.
	lang, err := collectLangPages(filepath.Join(repoRoot, "doc", "samples"), filepath.Join(repoRoot, "samples"))
	if err != nil {
		return err
	}

	// Gadx template docs live in the ./gadx submodule. When it is checked out,
	// publish them as their own "Gadx" nav section (prefixed pages + copied
	// image assets); when it is absent the section is simply omitted.
	gadxDir := filepath.Join(repoRoot, "gadx", "docs")
	gadxPages, err := collectGadxPages(gadxDir, gadxOrder)
	if err != nil {
		return err
	}
	if len(gadxPages) > 0 {
		if err := copyGadxAssets(gadxDir, outDir); err != nil {
			return err
		}
	}

	download := &page{Slug: "download", Title: "Download", OutFile: "download.html", Section: "Download"}
	wasmEmbed := &page{Slug: "wasm-embed", Title: "Embed the WASM", OutFile: "wasm-embed.html", Section: "Integrate"}

	// JS module docs (web/*/README.md) become the "JS modules" nav section, one
	// page per package at /js-modules/<name>.
	jsPages, err := collectJSModulePages(repoRoot)
	if err != nil {
		return err
	}

	// The "Playground" menu hosts the full ide-vuetify demo app (Playground /
	// Notebook / IDE tabs) built into /playground when a WASM build is requested
	// and bun is available. When that build is unavailable (e.g. bun missing), we
	// fall back to the simple in-page WASM playground so the menu still works.
	demoBuilt := false
	if buildWASM {
		if err := buildEmbeddedIDE(repoRoot, outDir, "playground"); err != nil {
			fmt.Fprintf(os.Stderr, "warning: full ide-vuetify demo unavailable, using the simple playground: %v\n", err)
		} else {
			demoBuilt = true
		}
	}
	var play *page
	if demoBuilt {
		// The demo is a standalone Vite app with its own index.html; link to it.
		play = &page{Slug: "playground", Title: "Playground", OutFile: "playground/index.html", Section: "Playground"}
	} else {
		play = &page{Slug: "playground", Title: "Playground", OutFile: "playground.html", Section: "Playground"}
	}
	cfg.playHref = play.OutFile

	// PrismJS bundle for static syntax highlighting (best-effort; needs bun).
	if err := buildPrismBundle(repoRoot, outDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: syntax highlighting disabled (prism bundle): %v\n", err)
	} else {
		cfg.prism = true
	}

	groups := []navGroup{
		{Name: "Guide", Pages: guide},
	}
	if len(lang) > 0 {
		groups = append(groups, navGroup{Name: "Language", Pages: lang})
	}
	groups = append(groups, navGroup{Name: "Reference", Pages: ref})
	if len(stdlib) > 0 {
		groups = append(groups, navGroup{Name: "Standard Library", Pages: stdlib})
	}
	if len(gadxPages) > 0 {
		groups = append(groups, navGroup{Name: "Gadx", Pages: gadxPages})
	}
	if len(jsPages) > 0 {
		groups = append(groups, navGroup{Name: "JS modules", Pages: jsPages})
	}
	groups = append(groups, navGroup{Name: "Integrate", Pages: []*page{wasmEmbed}})
	groups = append(groups, navGroup{Name: "Playground", Pages: []*page{play}})
	groups = append(groups, navGroup{Name: "Download", Pages: []*page{download}})

	// The Download and WASM-embedding guide carry custom bodies; render them into
	// the page model so they become routed doc pages in the SPA.
	download.BodyHTML = downloadBody(cfg)
	wasmEmbed.BodyHTML = wasmEmbedBody(play.OutFile)

	// Build the Vue + Vuetify docs shell (web/website) and drop the doc data,
	// logo, prism bundle and WASM assets next to it. content.json is written right
	// after the app is copied — overwriting the app's bundled development sample —
	// and before the (optional, fallible) WASM build, so a WASM failure can never
	// leave the site serving the placeholder content.
	if err := buildWebsiteSPA(repoRoot, outDir); err != nil {
		return fmt.Errorf("building website app: %w", err)
	}
	if err := writeContent(outDir, groups, cfg); err != nil {
		return err
	}
	if err := copyLogo(repoRoot, outDir); err != nil {
		return err
	}
	if buildWASM {
		if err := buildWASMAssets(repoRoot, outDir); err != nil {
			return fmt.Errorf("building wasm: %w", err)
		}
	}
	return nil
}

func collectPages(dir string, order []string, section string, isGuide bool) ([]*page, error) {
	var pages []*page
	for _, name := range order {
		path := filepath.Join(dir, name+".md")
		src, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue // tolerate missing optional pages
			}
			return nil, err
		}
		body, headings := renderMarkdown(string(src))
		title := firstHeading(headings)
		if title == "" {
			title = name
		}
		out := name + ".html"
		slug := name
		if isGuide && name == "README" {
			out = "index.html"
			slug = "index"
			title = "Gad Language"
		} else if !isGuide {
			out = "ref-" + name + ".html"
			slug = "ref-" + name
		}
		pages = append(pages, &page{
			Slug:     slug,
			Title:    title,
			OutFile:  out,
			Section:  section,
			BodyHTML: template.HTML(body),
			Headings: headings,
			plain:    plainText(string(src)),
		})
	}
	return pages, nil
}

// collectStdlibPages renders the standard-library module references found in
// dir (doc/stdlib) into the "Stdlib" nav submenu, one page per module in order.
// Each page keeps the stable `ref-stdlib-<module>` slug/route so existing links
// are preserved after the docs moved from doc/stdlib-<module>.md to
// doc/stdlib/<module>.md.
func collectStdlibPages(dir string, order []string) ([]*page, error) {
	var pages []*page
	for _, mod := range order {
		path := filepath.Join(dir, mod+".md")
		src, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue // tolerate a missing optional module page
			}
			return nil, err
		}
		body, headings := renderMarkdown(string(src))
		title := firstHeading(headings)
		if title == "" {
			title = mod
		}
		slug := "ref-stdlib-" + mod
		pages = append(pages, &page{
			Slug:     slug,
			Title:    title,
			OutFile:  slug + ".html",
			Section:  "Stdlib",
			BodyHTML: template.HTML(body),
			Headings: headings,
			plain:    plainText(string(src)),
		})
	}
	return pages, nil
}

// gadxLinkRe matches Markdown links to a sibling `.md` doc (no scheme, no path
// separator), so intra-gadx links can be rewritten to the prefixed output names.
var gadxLinkRe = regexp.MustCompile(`\]\(([A-Za-z0-9_-]+)\.md(#[A-Za-z0-9_-]+)?\)`)

// collectGadxPages renders the Gadx docs found in dir (in order) into pages named
// `gadx-<name>.html`. Intra-doc `.md` links are rewritten to the same prefixed
// names so cross-references resolve within the generated site; missing pages are
// tolerated (the submodule may not be checked out).
func collectGadxPages(dir string, order []string) ([]*page, error) {
	var pages []*page
	for _, name := range order {
		path := filepath.Join(dir, name+".md")
		src, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		// Rewrite `](other.md)` / `](other.md#anchor)` to `](gadx-other.html…)`.
		rewritten := gadxLinkRe.ReplaceAllString(string(src), "](gadx-$1.html$2)")
		body, headings := renderMarkdown(rewritten)
		title := firstHeading(headings)
		if title == "" {
			title = name
		}
		pages = append(pages, &page{
			Slug:     "gadx-" + name,
			Title:    title,
			OutFile:  "gadx-" + name + ".html",
			Section:  "Gadx",
			BodyHTML: template.HTML(body),
			Headings: headings,
			plain:    plainText(rewritten),
		})
	}
	return pages, nil
}

// langLinkRe matches a Markdown link to a sibling sample file (a `.gad`/`.gadt`/
// `.gadx`/`.md` target, no scheme) so the cross-references the samples use
// (`[03_functions.gad](03_functions.gad)`, `[classes](class/classes.gad)`,
// `[..](../24_interfaces.gad)`) resolve to the flat `lang-<slug>.html` pages. The
// path may contain `/` and `.` for links into and out of sample subdirectories.
var langLinkRe = regexp.MustCompile(`\]\(([0-9A-Za-z_./-]+)\.(?:gad|gadt|gadx|md)(#[A-Za-z0-9_-]+)?\)`)

// langSlug is the flat page slug for a language chapter name, which may carry a
// subdirectory (`class/classes` -> `lang-class-classes`).
func langSlug(name string) string {
	return "lang-" + strings.ReplaceAll(name, "/", "-")
}

// rewriteLangLinks rewrites the sample-to-sample markdown links in a chapter to
// the flat `lang-<slug>.html` pages, resolving each target relative to the
// chapter's own directory so links between the top level and subdirectories
// (e.g. samples/class/) point to the right page.
func rewriteLangLinks(src, pageName string) string {
	pageDir := path.Dir(pageName) // "." at the top level, "class" under class/
	return langLinkRe.ReplaceAllStringFunc(src, func(m string) string {
		sub := langLinkRe.FindStringSubmatch(m)
		target, frag := sub[1], sub[2]
		resolved := path.Clean(path.Join(pageDir, target))
		return "](" + langSlug(resolved) + ".html" + frag + ")"
	})
}

// collectLangPages renders the language chapters generated into doc/samples as the
// "Language" nav section. Pages are emitted as `lang-<name>.html`; intra-sample
// links (to `.gad`/`.gadt`/`.gadx`/`.md` siblings) are rewritten to the prefixed
// names. langOrder curates the ordering; any other doc/samples page is appended
// in name order so nothing is dropped. A missing dir yields no pages.
func collectLangPages(dir, samplesDir string) ([]*page, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	// Names present on disk (without .md). Top-level pages are always eligible;
	// pages one level down in a subdirectory (e.g. class/) are eligible only when
	// langOrder curates them, so the module/stdlib/testing sample subdirectories
	// (which have their own README sections) do not leak into the Language nav.
	present := map[string]bool{}
	topLevel := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() {
			subDir := filepath.Join(dir, e.Name())
			subEntries, subErr := os.ReadDir(subDir)
			if subErr != nil {
				continue
			}
			for _, se := range subEntries {
				if !se.IsDir() && strings.HasSuffix(se.Name(), ".md") {
					present[e.Name()+"/"+strings.TrimSuffix(se.Name(), ".md")] = true
				}
			}
			continue
		}
		if strings.HasSuffix(e.Name(), ".md") {
			name := strings.TrimSuffix(e.Name(), ".md")
			present[name] = true
			topLevel[name] = true
		}
	}
	var order []string
	seen := map[string]bool{}
	for _, n := range langOrder {
		if present[n] {
			order = append(order, n)
			seen[n] = true
		}
	}
	var rest []string
	for n := range topLevel {
		if !seen[n] {
			rest = append(rest, n)
		}
	}
	sort.Strings(rest)
	order = append(order, rest...)

	var (
		pages  []*page
		readme *page
	)
	for _, name := range order {
		src, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(name)+".md"))
		if err != nil {
			return nil, err
		}
		rewritten := rewriteLangLinks(string(src), name)
		body, headings := renderMarkdown(rewritten)
		title := firstHeading(headings)
		if title == "" {
			title = name
		}
		slug := langSlug(name)
		p := &page{
			Slug:     slug,
			Title:    title,
			OutFile:  slug + ".html",
			Section:  "Language",
			BodyHTML: template.HTML(body),
			Headings: headings,
			plain:    plainText(rewritten),
		}
		if name == "README" {
			p.Title = "Language Chapters"
			readme = p
		} else if code, lang, ok := readSample(samplesDir, name); ok {
			// Attach the runnable sample source that backs this chapter.
			p.Source = code
			p.SourceLang = lang
			p.SourcePath = "samples/" + name + "." + lang
		}
		pages = append(pages, p)
	}
	// Replace the auto-generated "samples/Files" README with a clean index that
	// links each chapter by its title (no filenames, no "samples" heading).
	if readme != nil {
		readme.BodyHTML = langIndexHTML(pages)
		readme.Headings = nil
	}
	return pages, nil
}

// readSample returns the source of the sample file backing a language chapter
// (samples/<name>.<gad|gadt|gadx>) and its PrismJS language, or ok=false when no
// source file exists.
func readSample(samplesDir, name string) (code, lang string, ok bool) {
	for _, ext := range []string{".gad", ".gadt", ".gadx"} {
		if data, err := os.ReadFile(filepath.Join(samplesDir, name+ext)); err == nil {
			return string(data), strings.TrimPrefix(ext, "."), true
		}
	}
	return "", "", false
}

// langIndexHTML builds the "Language Chapters" landing: a short lead-in and a list
// of the chapters linked by title.
func langIndexHTML(pages []*page) template.HTML {
	var b strings.Builder
	b.WriteString(`<h1>Language Chapters</h1>`)
	b.WriteString(`<p>A guided tour of the Gad language, one topic per chapter. Every chapter is a runnable example — open one and use <strong>View source</strong> to read the code it is generated from.</p>`)
	b.WriteString(`<ul class="chapter-index">`)
	for _, p := range pages {
		if p.Slug == "lang-README" {
			continue
		}
		fmt.Fprintf(&b, `<li><a href="%s">%s</a></li>`, p.OutFile, template.HTMLEscapeString(p.Title))
	}
	b.WriteString(`</ul>`)
	return template.HTML(b.String())
}

// copyGadxAssets copies non-Markdown files (images such as the benchmark SVGs)
// from the Gadx docs directory into the site root, where the prefixed Gadx pages
// reference them by their original relative names.
func copyGadxAssets(dir, outDir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(outDir, e.Name()), data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// jsModules are the publishable web packages documented under "JS modules". Dir
// is the package's path from the repo root (the editor plugins live under
// plugins/, the IDE components under web/).
// Site, when set, is the package's own documentation site: the nav entry links
// out to it (a plain external link) instead of rendering the README as an
// in-site page — used for the editor plugins that ship a full GitHub Pages site.
var jsModules = []struct{ Name, Title, Dir, Site string }{
	{"codemirror-gad", "@gad-lang/codemirror-gad", "web/plugins/js/codemirror-gad", "https://gad-lang.github.io/codemirror-gad/"},
	{"prism-gad", "@gad-lang/prism-gad", "web/plugins/js/prism-gad", "https://gad-lang.github.io/prism-gad/"},
	{"ide-react", "@gad-lang/ide-react", "web/ide-react", ""},
	{"ide-vuetify", "@gad-lang/ide-vuetify", "web/ide-vuetify", ""},
}

// mdLinkRe matches Markdown link targets `](target)`.
var mdLinkRe = regexp.MustCompile(`\]\(([^)]+)\)`)

// rewriteModuleLinks rewrites a module README's relative links to absolute GitHub
// URLs (rooted at web/<name>/), so its `./docs/*.md`, `../<pkg>` and example
// links resolve on the docs site. External, anchor and absolute links are left
// as-is.
func rewriteModuleLinks(md, dir string) string {
	return mdLinkRe.ReplaceAllStringFunc(md, func(m string) string {
		target := m[2 : len(m)-1]
		if strings.HasPrefix(target, "http://") || strings.HasPrefix(target, "https://") ||
			strings.HasPrefix(target, "#") || strings.HasPrefix(target, "mailto:") || strings.HasPrefix(target, "/") {
			return m
		}
		anchor := ""
		if i := strings.IndexByte(target, '#'); i >= 0 {
			anchor, target = target[i:], target[:i]
		}
		resolved := path.Join(dir, target)
		return "](https://github.com/gad-lang/gad/blob/main/" + resolved + anchor + ")"
	})
}

// collectJSModulePages renders each web module's README into a page at
// js-modules/<name>.html (the "JS modules" nav section). A missing package is
// tolerated.
func collectJSModulePages(repoRoot string) ([]*page, error) {
	var pages []*page
	for _, m := range jsModules {
		// Packages with their own docs site become an external nav link (no body),
		// pointing at that site instead of an in-site README page.
		if m.Site != "" {
			pages = append(pages, &page{
				Slug:    "js-modules-" + m.Name,
				Title:   m.Title,
				OutFile: m.Site, // absolute URL → external link in the nav
				Section: "JS modules",
			})
			continue
		}
		fp := filepath.Join(repoRoot, filepath.FromSlash(m.Dir), "README.md")
		src, err := os.ReadFile(fp)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		md := rewriteModuleLinks(string(src), m.Dir)
		body, headings := renderMarkdown(md)
		pages = append(pages, &page{
			Slug:     "js-modules-" + m.Name,
			Title:    m.Title,
			OutFile:  "js-modules/" + m.Name + ".html",
			Section:  "JS modules",
			BodyHTML: template.HTML(body),
			Headings: headings,
			plain:    plainText(md),
		})
	}
	return pages, nil
}

// buildEmbeddedIDE builds the server-less Vuetify IDE demo (the full app:
// Playground / Notebook / IDE tabs) with a relative base and copies its output
// into <outDir>/<subDir>, so the docs site serves it in-browser. Requires bun
// and the workspace to be installed; the caller tolerates failure.
func buildEmbeddedIDE(repoRoot, outDir, subDir string) error {
	demo := filepath.Join(repoRoot, "web", "ide-vuetify", "demo")
	if _, err := os.Stat(demo); err != nil {
		return fmt.Errorf("demo not found: %w", err)
	}
	// `bun run samples` regenerates src/samples.gen.ts (git-ignored, baked from
	// the repo samples/ tree) — the demo's own build runs it via predev/build, but
	// we invoke vite directly here, so run it explicitly first.
	cmd := exec.Command("bash", "-c", "bun run samples && bun run wasm && bunx vite build --base=./")
	cmd.Dir = demo
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("%v: %s", err, out)
	}
	return copyTree(filepath.Join(demo, "dist"), filepath.Join(outDir, subDir))
}

// copyTree recursively copies the directory src into dst.
func copyTree(src, dst string) error {
	return filepath.Walk(src, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		in, err := os.Open(p)
		if err != nil {
			return err
		}
		defer in.Close()
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		out, err := os.Create(target)
		if err != nil {
			return err
		}
		defer out.Close()
		_, err = io.Copy(out, in)
		return err
	})
}

func firstHeading(hs []Heading) string {
	for _, h := range hs {
		if h.Level == 1 {
			return h.Text
		}
	}
	if len(hs) > 0 {
		return hs[0].Text
	}
	return ""
}

// plainText strips markdown to plain text for the search index.
func plainText(src string) string {
	var b strings.Builder
	inCode := false
	for _, line := range strings.Split(src, "\n") {
		if strings.HasPrefix(strings.TrimRight(line, " "), "```") {
			inCode = !inCode
			continue
		}
		l := line
		if !inCode {
			l = strings.TrimLeft(l, "#>-*| ")
		}
		l = stripInline(l)
		if strings.TrimSpace(l) != "" {
			b.WriteString(l)
			b.WriteByte(' ')
		}
	}
	return strings.Join(strings.Fields(b.String()), " ")
}

// downloadAsset is one row of the Download page's asset table.
type downloadAsset struct {
	label string // human label, e.g. "Linux (amd64)"
	name  string // file name, e.g. gad_1.2.3_linux_amd64.tar.gz
	url   string // download URL
	desc  string // short description
	local bool   // served directly from the site (download attribute)
}

// downloadBody renders the Download page: a highlighted release banner, the
// release notes, and a table of downloadable assets (CLI binaries for
// linux/windows on amd64/arm64, both WASM modules, and checksums).
func downloadBody(cfg siteConfig) template.HTML {
	var b strings.Builder

	// Release banner — the release name is shown prominently.
	b.WriteString(`<div class="rel-hero">`)
	if cfg.hasRelease() {
		b.WriteString(`<div class="rel-badge">Release</div>`)
		fmt.Fprintf(&b, `<h1 class="rel-name"><a href="%s">%s</a></h1>`,
			template.HTMLEscapeString(cfg.releaseURL()), template.HTMLEscapeString(cfg.releaseName()))
		if cfg.ReleaseDate != "" {
			fmt.Fprintf(&b, `<div class="rel-date">%s</div>`, template.HTMLEscapeString(cfg.ReleaseDate))
		}
	} else {
		b.WriteString(`<div class="rel-badge">Latest</div>`)
		fmt.Fprintf(&b, `<h1 class="rel-name"><a href="%s">Latest release</a></h1>`,
			template.HTMLEscapeString(cfg.releaseURL()))
		b.WriteString(`<div class="rel-date">This is a development build; download links point at the latest published release.</div>`)
	}
	b.WriteString(`</div>`)

	// Release notes (rendered Markdown).
	if strings.TrimSpace(cfg.ReleaseNotes) != "" {
		notes, _ := renderMarkdown(cfg.ReleaseNotes)
		b.WriteString(`<section class="rel-notes"><h2>Release notes</h2>`)
		b.WriteString(notes)
		b.WriteString(`</section>`)
	}

	ver := strings.TrimPrefix(cfg.ReleaseTag, "v")
	archiveName := func(goos, arch string) string {
		ext := "tar.gz"
		if goos == "windows" {
			ext = "zip"
		}
		return fmt.Sprintf("gad_%s_%s_%s.%s", ver, goos, arch, ext)
	}

	// CLI binaries (goreleaser archives). Names include the version only when a
	// release tag is known; otherwise the "latest/download/<name>" URL resolves
	// server-side, so we still show a stable label.
	bins := []struct{ label, goos, arch, desc string }{
		{"Linux (amd64)", "linux", "amd64", "64-bit Intel/AMD Linux"},
		{"Linux (arm64)", "linux", "arm64", "64-bit ARM Linux"},
		{"Windows (amd64)", "windows", "amd64", "64-bit Intel/AMD Windows"},
		{"Windows (arm64)", "windows", "arm64", "64-bit ARM Windows"},
	}
	var assets []downloadAsset
	for _, bn := range bins {
		name := archiveName(bn.goos, bn.arch)
		assets = append(assets, downloadAsset{label: bn.label, name: name, url: cfg.assetURL(name), desc: bn.desc})
	}
	// WebAssembly module — served directly from the site (it is built into the
	// output dir), so it downloads even without a published release.
	assets = append(assets,
		downloadAsset{label: "WebAssembly", name: "gad.wasm", url: "gad.wasm", desc: "Browser/WASM module (run, format, diagnostics and the gadDebug* debugger)", local: true},
	)
	if cfg.hasRelease() {
		assets = append(assets, downloadAsset{label: "Checksums", name: "checksums.txt", url: cfg.assetURL("checksums.txt"), desc: "SHA-256 checksums of the release assets"})
	}

	b.WriteString(`<h2>Assets</h2><div class="dl-table"><table><thead><tr><th>Platform</th><th>File</th><th>Description</th></tr></thead><tbody>`)
	for _, a := range assets {
		dl := ""
		if a.local {
			dl = ` download`
		}
		fmt.Fprintf(&b, `<tr><td>%s</td><td><a href="%s"%s><code>%s</code></a></td><td>%s</td></tr>`,
			template.HTMLEscapeString(a.label), template.HTMLEscapeString(a.url), dl,
			template.HTMLEscapeString(a.name), template.HTMLEscapeString(a.desc))
	}
	b.WriteString(`</tbody></table></div>`)

	fmt.Fprintf(&b, `<p class="muted">All release assets are on the <a href="%s">GitHub releases page</a>.</p>`,
		template.HTMLEscapeString(cfg.releaseURL()))

	return template.HTML(b.String())
}

// codeBlock renders code as an HTML-escaped <pre><code> block, tagging both with
// a language-<lang> class so PrismJS highlights it.
func codeBlock(code, lang string) string {
	cls := ""
	if lang != "" {
		cls = ` class="language-` + lang + `"`
	}
	return "<pre" + cls + "><code" + cls + ">" + template.HTMLEscapeString(code) + "</code></pre>"
}

// wasmEmbedBody renders the "Embed the WASM" page: how to load the module and
// the JS API it exposes. playHref is the Playground/demo path (Web Worker note).
func wasmEmbedBody(playHref string) template.HTML {
	var b strings.Builder
	b.WriteString(`<h1>Embed the Gad WASM in your site</h1>`)
	b.WriteString(`<p>The Gad WebAssembly module runs the compiler, VM, formatter, doc extractor and debugger entirely in the browser — no server. It installs a small set of functions on the JS global object, each taking strings and returning a JSON string.</p>`)

	b.WriteString(`<h2>1. Get the files</h2>`)
	b.WriteString(`<p>Download <code>gad.wasm</code> and <code>wasm_exec.js</code> from the <a href="download.html">Download</a> page (both are attached to every release). <code>wasm_exec.js</code> is Go's WASM loader and must match the Go toolchain the module was built with — always ship the one from the same release.</p>`)

	b.WriteString(`<h2>2. Load it</h2>`)
	b.WriteString(codeBlock("<script src=\"wasm_exec.js\"></script>\n<script>\n  const go = new Go();\n  WebAssembly.instantiateStreaming(fetch(\"gad.wasm\"), go.importObject)\n    .then(r => { go.run(r.instance); onReady(); });\n\n  function onReady() {\n    // window.gadRun / gadFormat / gadDiagnose / gadDoc / … are ready.\n    const r = JSON.parse(gadRun('println(\"hi\"); return 6 * 7'));\n    console.log(r.stdout, r.result); // \"hi\\n\" \"42\"\n  }\n</script>", "markup"))
	fmt.Fprintf(&b, `<blockquote>A long-running script blocks the thread. For a responsive UI, load the module inside a <strong>Web Worker</strong> — exactly what the <a href="%s">Playground</a> does.</blockquote>`, template.HTMLEscapeString(playHref))

	b.WriteString(`<h2>3. The API</h2>`)
	b.WriteString(`<p>Each function returns a JSON string. <code>sourceType</code> selects the dialect: <code>""</code>/<code>"gad"</code> (plain Gad), <code>"gadTemplate"</code> (mixed <code>.gadt</code>) or <code>"gadx"</code>.</p>`)
	b.WriteString(`<div class="dl-table"><table><thead><tr><th>Function</th><th>Returns (JSON)</th></tr></thead><tbody>`)
	rows := [][2]string{
		{`gadRun(src[, sourceType[, argsJSON]])`, `{ ok, stdout, stderr, result, diagnostics }`},
		{`gadFormat(src[, sourceType])`, `{ ok, source, diagnostics }`},
		{`gadDiagnose(src[, sourceType])`, `{ diagnostics: [{line, column, message, severity}] }`},
		{`gadDoc(src, sourceType)`, `{ markdown } | { error }`},
		{`gadDocData(src, sourceType)`, `{ doc } | { error }`},
		{`gadEval(src, expr, repr)`, `{ ok, value, error, stdout }`},
		{`gadTranspile(src, mixed)`, `{ ok, source, diagnostics }`},
		{`gadInspect(session, expr, src)`, `{ ok, inspect } | { ok:false, error }`},
		{`gadDebugStart / gadDebugCommand / gadDebugEval / gadDebugStop`, `debugger stepping protocol`},
	}
	for _, r := range rows {
		fmt.Fprintf(&b, `<tr><td><code>%s</code></td><td><code>%s</code></td></tr>`,
			template.HTMLEscapeString(r[0]), template.HTMLEscapeString(r[1]))
	}
	b.WriteString(`</tbody></table></div>`)

	b.WriteString(`<h2>Prefer a ready-made editor?</h2>`)
	b.WriteString(`<p>The <a href="js-modules/ide-vuetify.html">@gad-lang/ide-vuetify</a> and <a href="js-modules/ide-react.html">@gad-lang/ide-react</a> packages wrap this module into a full IDE component (editor, run profiles, debugger, inspector), and <a href="https://gad-lang.github.io/codemirror-gad/" target="_blank" rel="noopener">@gad-lang/codemirror-gad</a> / <a href="https://gad-lang.github.io/prism-gad/" target="_blank" rel="noopener">@gad-lang/prism-gad</a> provide syntax highlighting.</p>`)
	return template.HTML(b.String())
}

// buildPrismBundle bundles PrismJS core + common languages + the Gad-family
// grammars (gad / gadt / gadx) into <outDir>/prism.js for static syntax
// highlighting. Requires bun; the caller tolerates failure (code blocks then
// render unstyled).
func buildPrismBundle(repoRoot, outDir string) error {
	pkg := filepath.Join(repoRoot, "web", "plugins", "js", "prism-gad")
	if _, err := os.Stat(filepath.Join(pkg, "site-bundle.mjs")); err != nil {
		return err
	}
	// bun runs from the package dir (to resolve prismjs + ./src); the outfile must
	// be absolute so it lands in the site output, not under the package.
	out, err := filepath.Abs(filepath.Join(outDir, "prism.js"))
	if err != nil {
		return err
	}
	cmd := exec.Command("bun", "build", "./site-bundle.mjs", "--outfile", out, "--minify", "--format=iife")
	cmd.Dir = pkg
	if o, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("%v: %s", err, o)
	}
	return nil
}

// copyLogo copies the Gad logo (assets/identity/gad.svg) into the site root as
// gad.svg (header brand, favicon, home hero). A missing logo is tolerated.
func copyLogo(repoRoot, outDir string) error {
	src := filepath.Join(repoRoot, "assets", "identity", "gad.svg")
	data, err := os.ReadFile(src)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "gad.svg"), data, 0o644)
}

// buildWASMAssets compiles the Gad WASM module (gad.wasm, debugger-enabled) and
// copies wasm_exec.js into the output directory so the Playground works offline /
// on GitHub Pages and the Download page can offer it.
func buildWASMAssets(repoRoot, outDir string) error {
	cmd := exec.Command("go", "build", "-o", filepath.Join(outDir, "gad.wasm"), "./web/wasm")
	cmd.Dir = repoRoot
	cmd.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gad.wasm: %v: %s", err, out)
	}

	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return err
	}
	root := strings.TrimSpace(string(goroot))
	for _, cand := range []string{
		filepath.Join(root, "lib", "wasm", "wasm_exec.js"),
		filepath.Join(root, "misc", "wasm", "wasm_exec.js"),
	} {
		if data, err := os.ReadFile(cand); err == nil {
			return os.WriteFile(filepath.Join(outDir, "wasm_exec.js"), data, 0o644)
		}
	}
	return fmt.Errorf("wasm_exec.js not found under %s", root)
}
