name: test

on:
  push:
    branches: 
      - main
      - development
      - release/*
  pull_request:
    branches:
      - main
      - development

jobs:
  build-old:
      strategy:
        matrix:
          os:  [ 'ubuntu-latest', 'macOS-latest' ]
          go: [ '1.15', '1.16' ]
      runs-on: ${{ matrix.os }}
      name: Test and Build for Go ${{ matrix.go }}  ${{ matrix.os }}

      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install Staticcheck
        run: |
          GOBIN=${GOBIN:-"$HOME/go/bin"}
          mkdir -p "$GOBIN"
          echo "$GOBIN" >> "$GITHUB_PATH"
          export GO111MODULE=on
          cd "$GOBIN" && go get honnef.co/go/tools/cmd/staticcheck@2021.1

      - name: Test
        run: make test

      - name: Build CLI
        run: make build-cli

  build-new:
    strategy:
      matrix:
        os:  [ 'ubuntu-latest', 'macOS-latest' ]
        go: [ '1.17', '1.18' ]
    runs-on: ${{ matrix.os }}
    name: Test and Build for Go ${{ matrix.go }}  ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Install Staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2022.1

    - name: Test
      run: make test

    - name: Build CLI
      run: |
        make build-cli
        mv ugo ugo_go${{ matrix.go }}_$(go env GOOS)_$(go env GOARCH)
    
    - uses: actions/upload-artifact@v3
      with:
        path: ugo_go*
        if-no-files-found: error
        retention-days: 7
