name: test

on:
  push:
    branches: 
      - main
      - development
      - release/*
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.17', '1.18' ]
    name: Test and Build for Go ${{ matrix.go }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Get Dependencies
      run: go get -v -t -d ./...
    
    - name: Install Staticcheck
      run: go get -u honnef.co/go/tools/cmd/staticcheck

    - name: Test
      run: make test

    - name: Build CLI
      run: make build-cli
