name: test

on:
  push:
    branches: 
      - main
      - development
      - release/*
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    strategy:
      matrix:
        os:  [ 'ubuntu-latest', 'macOS-latest' ]
        go: [ '1.15', '1.16', '1.17', '1.18' ]
    runs-on: ${{ matrix.os }}
    name: Test and Build for Go ${{ matrix.go }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: '2022.1'
        install-go: false
        cache-key: ${{ matrix.go }}

    - name: Test
      run: make test

    - name: Build CLI
      run: make build-cli
